-- ============================================
-- V10__legacy_tb_offline.sql
-- 윌비스 오프라인 강의/주문/사물함
-- 대상 테이블: 18개 (tb_off_lec_mst, tb_off_lec_bridge, tb_off_lec_jong, tb_off_lecture_date, tb_off_mylecture...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_off_lec_mst ===========
CREATE TABLE tb_off_lec_mst (
  seq BIGINT,
  leccode varchar(30),
  category_cd varchar(20),
  learning_cd varchar(20),
  subject_type varchar(1),
  subject_gubun varchar(1),
  subject_member_cnt BIGINT,
  subject_teacher varchar(30),
  subject_teacher_payment varchar(50),
  subject_sjt_cd varchar(50),
  subject_title varchar(1000),
  subject_desc BYTEA,
  subject_keyword varchar(600),
  subject_open_date varchar(8),
  lec_schedule varchar(20),
  week1 varchar(1),
  week2 varchar(1),
  week3 varchar(1),
  week4 varchar(1),
  week5 varchar(1),
  week6 varchar(1),
  week7 varchar(1),
  subject_discount BIGINT,
  subject_price BIGINT,
  subject_real_price BIGINT,
  subject_sumnail varchar(1000),
  subject_isuse varchar(1),
  lec_type_choice varchar(1),
  lec_gubun varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  subject_teacher_movie_payment varchar(50),
  plan BYTEA,
  rec_gubun varchar(1)
);


-- =========== tb_off_lec_bridge ===========
CREATE TABLE tb_off_lec_bridge (
  seq BIGINT,
  bridge_leccode varchar(30),
  leccode varchar(30),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_off_lec_jong ===========
CREATE TABLE tb_off_lec_jong (
  seq BIGINT,
  leccode varchar(30),
  mst_leccode varchar(30),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  sort BIGINT,
  gubun varchar(1)
);


-- =========== tb_off_lecture_date ===========
CREATE TABLE tb_off_lecture_date (
  leccode varchar(30),
  num BIGINT,
  lec_date date
);


-- =========== tb_off_mylecture ===========
CREATE TABLE tb_off_mylecture (
  userid varchar(30),
  orderno varchar(20),
  package_no varchar(20),
  lecture_no varchar(20),
  start_date date,
  end_date date,
  period BIGINT,
  study_percent BIGINT,
  stop_lecture varchar(1),
  free_id varchar(30),
  plus_buy BIGINT,
  playyn varchar(1),
  reg_dt date,
  add_length BIGINT,
  firststart_date date,
  realprice BIGINT
);


-- =========== tb_off_orders ===========
CREATE TABLE tb_off_orders (
  orderno varchar(20),
  user_id varchar(30),
  user_nm varchar(50),
  zip_code varchar(7),
  address1 varchar(200),
  email varchar(50),
  reg_dt date,
  tid varchar(30),
  ipdate date,
  free_movie varchar(10),
  off_line varchar(1),
  address2 varchar(200),
  reg_id varchar(30),
  order_type varchar(5),
  ticket_print_dt date
);


-- =========== tb_off_approvals ===========
CREATE TABLE tb_off_approvals (
  orderno varchar(20),
  price BIGINT,
  addprice BIGINT,
  paycode varchar(6),
  acctnocode varchar(6),
  payname varchar(50),
  point BIGINT,
  returnvalue varchar(2000),
  reg_dt date,
  banner_name varchar(40),
  reprice BIGINT,
  repricedate date,
  orderurl varchar(10),
  vcdbank varchar(2),
  vacct varchar(30),
  vacct_name varchar(30),
  refund_point BIGINT,
  price_card BIGINT,
  price_cash BIGINT,
  price_bank BIGINT,
  price_unpaid BIGINT,
  price_discount BIGINT,
  price_discount_type varchar(10),
  price_discount_reason varchar(500),
  card_name varchar(40),
  due_dt date,
  tid varchar(50),
  memo varchar(2000)
);


-- =========== tb_off_order_mgnt_no ===========
CREATE TABLE tb_off_order_mgnt_no (
  orderno varchar(20),
  mgntno varchar(20),
  iscancel BIGINT,
  cnt BIGINT,
  price BIGINT,
  statuscode varchar(6),
  canceldate date,
  confirmdate date,
  sdate varchar(10),
  isconfirm date,
  repayment_day date,
  repayment_price BIGINT,
  memo varchar(4000),
  confirmid varchar(20),
  wmv_pmp varchar(10),
  user_package_flag varchar(1),
  orderurl varchar(30),
  open_admin_id varchar(30),
  discountper BIGINT,
  spo varchar(20),
  reg_id varchar(30),
  reg_dt date,
  ptype varchar(2),
  seq BIGINT
);


-- =========== tb_off_refund ===========
CREATE TABLE tb_off_refund (
  idx BIGINT,
  order_id varchar(20),
  refund_pay BIGINT,
  set_yn varchar(1),
  set_date date,
  reg_date date NOT NULL,
  acc_bank_name varchar(30),
  acc_bank_num varchar(30),
  refund_card BIGINT,
  refund_cash BIGINT,
  refund_memo varchar(300),
  acc_bank_depositor varchar(50)
);


-- =========== tb_off_cc_cart ===========
CREATE TABLE tb_off_cc_cart (
  seq BIGINT,
  user_id varchar(20),
  leccode varchar(30),
  kind_type varchar(1),
  rsc_id varchar(30),
  rsc_type varchar(1),
  movie_type varchar(2),
  regdate date,
  reprice BIGINT,
  package_period BIGINT,
  sdate varchar(50),
  edate varchar(50),
  book_count BIGINT,
  orderno varchar(20)
);


-- =========== tb_off_cc_j_cart ===========
CREATE TABLE tb_off_cc_j_cart (
  seq BIGINT,
  leccode varchar(30),
  mst_leccode varchar(30),
  update_id varchar(30),
  reg_dt date,
  price BIGINT,
  kind_type varchar(1)
);


-- =========== tb_off_choice_jong_no ===========
CREATE TABLE tb_off_choice_jong_no (
  seq BIGINT,
  leccode varchar(30),
  no BIGINT,
  category_cd varchar(100)
);


-- =========== tb_off_plus_ca_book ===========
CREATE TABLE tb_off_plus_ca_book (
  idx BIGINT,
  leccode varchar(30),
  rsc_id varchar(20),
  flag varchar(1)
);


-- =========== tb_off_box ===========
CREATE TABLE tb_off_box (
  box_cd varchar(10),
  box_nm varchar(200),
  box_count BIGINT,
  box_price BIGINT,
  deposit BIGINT,
  row_count BIGINT,
  row_num BIGINT,
  update_dt date,
  update_id varchar(30),
  start_num BIGINT,
  end_num BIGINT
);


-- =========== tb_off_box_num ===========
CREATE TABLE tb_off_box_num (
  box_cd varchar(10),
  box_num BIGINT,
  userid varchar(30),
  box_flag varchar(1),
  update_dt date,
  update_id varchar(30),
  rent_seq BIGINT,
  rent_memo varchar(500)
);


-- =========== tb_off_box_rent ===========
CREATE TABLE tb_off_box_rent (
  box_cd varchar(10),
  seq BIGINT,
  box_num BIGINT,
  userid varchar(30),
  rent_start date,
  rent_end date,
  deposit BIGINT,
  deposit_yn varchar(20),
  extend_yn varchar(20),
  key_yn varchar(20),
  update_dt date,
  update_id varchar(30),
  rent_type varchar(10),
  order_id varchar(20),
  pay_gubun varchar(20),
  deposit_refund BIGINT,
  rent_memo varchar(500)
);


-- =========== tb_off_room ===========
CREATE TABLE tb_off_room (
  room_cd varchar(10),
  room_nm varchar(200),
  room_count BIGINT,
  update_dt date,
  update_id varchar(30),
  start_num BIGINT,
  end_num BIGINT
);


-- =========== tb_off_room_num ===========
CREATE TABLE tb_off_room_num (
  room_cd varchar(10),
  room_num BIGINT,
  userid varchar(30),
  room_flag varchar(1),
  update_dt date,
  update_id varchar(30),
  rent_seq BIGINT,
  rent_memo varchar(500)
);


