-- ============================================
-- V11__legacy_tb_order.sql
-- 윌비스 온라인 주문/결제
-- 대상 테이블: 9개 (tb_orders, tb_torders, tb_approvals, tb_order_mgnt_no, tb_order_yearpackage...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_orders ===========
CREATE TABLE tb_orders (
  orderno varchar(20),
  user_id varchar(30),
  user_nm varchar(50),
  zip_code varchar(7),
  address1 varchar(200),
  email varchar(100),
  reg_dt date,
  tid varchar(30),
  ipdate date,
  free_movie varchar(10),
  off_line varchar(1),
  address2 varchar(200),
  reg_id varchar(30)
);


-- =========== tb_torders ===========
CREATE TABLE tb_torders (
  id BIGINT,
  orderno varchar(20),
  identyid varchar(20),
  examcode varchar(20),
  user_id varchar(30),
  user_nm varchar(50),
  receipttype BIGINT,
  examtype BIGINT,
  classcode varchar(20),
  classseriescode varchar(20),
  addpoint1 BIGINT,
  addpoint2 BIGINT,
  addpoint3 BIGINT,
  printflag BIGINT,
  printuser varchar(20),
  printtime date,
  note varchar(500),
  paymenttargetamount BIGINT,
  adddiscountratio BIGINT,
  adddiscountamount BIGINT,
  adddiscountreason varchar(100),
  paymentduedate varchar(20),
  paymentstate BIGINT,
  examstatus BIGINT,
  examstarttime date,
  examendtime date,
  examsparetime BIGINT,
  examip varchar(20),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_approvals ===========
CREATE TABLE tb_approvals (
  orderno varchar(20),
  price BIGINT,
  addprice BIGINT,
  paycode varchar(6),
  acctnocode varchar(6),
  payname varchar(50),
  point BIGINT,
  returnvalue varchar(2000),
  reg_dt date,
  banner_name varchar(40),
  reprice BIGINT,
  repricedate date,
  orderurl varchar(10),
  vcdbank varchar(2),
  vacct varchar(30),
  vacct_name varchar(30),
  refund_point BIGINT
);


-- =========== tb_order_mgnt_no ===========
CREATE TABLE tb_order_mgnt_no (
  orderno varchar(20),
  mgntno varchar(20),
  iscancel BIGINT,
  cnt BIGINT,
  price BIGINT,
  statuscode varchar(6),
  canceldate date,
  confirmdate date,
  sdate varchar(10),
  isconfirm date,
  repayment_day date,
  repayment_price BIGINT,
  memo varchar(4000),
  confirmid varchar(20),
  wmv_pmp varchar(10),
  user_package_flag varchar(1),
  orderurl varchar(30),
  open_admin_id varchar(30),
  discountper BIGINT,
  spo varchar(20),
  reg_id varchar(30),
  reg_dt date,
  ptype varchar(2),
  seq BIGINT,
  gift_yn varchar(3)
);


-- =========== tb_order_yearpackage ===========
CREATE TABLE tb_order_yearpackage (
  orderno varchar(20),
  package_no varchar(30),
  subject_teacher varchar(50),
  learning_cd varchar(20),
  reg_dt date,
  start_date date,
  end_date date
);


-- =========== tb_paysettlement ===========
CREATE TABLE tb_paysettlement (
  seq BIGINT,
  onoff varchar(4),
  teacher_id varchar(30),
  teacher_nm varchar(50),
  leccode varchar(30),
  preamount BIGINT,
  amount BIGINT,
  teacheramount BIGINT,
  deductamount BIGINT,
  calcucriteria_dtype varchar(4),
  calcucriteria_dvalue BIGINT,
  calcucriteria_jtype varchar(4),
  calcucriteria_jvalue BIGINT,
  teacherpay BIGINT,
  withholdratio BIGINT,
  withholdtax BIGINT,
  deductamount_etc BIGINT,
  adjustamount BIGINT,
  settle_dt date,
  reg_dt date
);


-- =========== tb_paysettlement_add ===========
CREATE TABLE tb_paysettlement_add (
  teacher_id varchar(30),
  leccode varchar(30),
  addtype varchar(2),
  addmemo varchar(100),
  addmoney BIGINT,
  addreg_dt date,
  addupd_dt date,
  etcyn varchar(2),
  psa_no BIGINT
);


-- =========== tb_seq_orderno ===========
CREATE TABLE tb_seq_orderno (
  gubun varchar(3),
  gyear BIGINT,
  seq BIGINT
);


-- =========== tb_seqoff_orderno ===========
CREATE TABLE tb_seqoff_orderno (
  gubun varchar(3),
  gyear BIGINT,
  seq BIGINT
);


