-- ============================================
-- V12__legacy_tb_book.sql
-- 윌비스 교재/배송
-- 대상 테이블: 4개 (tb_ca_book, tb_plus_ca_book, tb_comment_book, tb_delivers)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_ca_book ===========
CREATE TABLE tb_ca_book (
  seq BIGINT,
  rsc_id varchar(100),
  subject_sjt_cd varchar(1000),
  category_cd varchar(55),
  learning_cd varchar(20),
  book_nm varchar(4000),
  book_info BYTEA,
  book_memo varchar(4000),
  book_keyword varchar(4000),
  issue_date varchar(8),
  cover_type varchar(1),
  book_contents varchar(4000),
  price BIGINT,
  discount BIGINT,
  discount_price BIGINT,
  point BIGINT,
  book_publishers varchar(100),
  book_author varchar(50),
  book_supplementdata varchar(1),
  book_printingdate varchar(1),
  book_main varchar(1),
  book_sub varchar(1),
  book_studentbook varchar(1),
  attach_file varchar(100),
  attach_img_l varchar(100),
  attach_img_m varchar(100),
  attach_img_s varchar(100),
  attach_detail_info varchar(100),
  book_stock BIGINT,
  free_post varchar(1),
  book_date varchar(8),
  new_book varchar(1),
  main_view varchar(1),
  use_yn varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_plus_ca_book ===========
CREATE TABLE tb_plus_ca_book (
  idx BIGINT,
  leccode varchar(30),
  rsc_id varchar(20),
  flag varchar(1)
);


-- =========== tb_comment_book ===========
CREATE TABLE tb_comment_book (
  seq BIGINT,
  rsc_id varchar(100),
  user_id varchar(30),
  user_name varchar(50),
  title varchar(200),
  content varchar(4000),
  choice_point varchar(1),
  reg_dt date
);


-- =========== tb_delivers ===========
CREATE TABLE tb_delivers (
  orderno varchar(20),
  sendno varchar(50),
  username varchar(100),
  zipcd varchar(7),
  addr varchar(400),
  memo varchar(2000),
  regdate date NOT NULL,
  senddate date,
  dleorder varchar(6),
  charge INTEGER
);


