-- ============================================
-- V13__legacy_tb_cart_bookmark.sql
-- 윌비스 카트/북마크
-- 대상 테이블: 4개 (tb_cc_cart, tb_cc_j_cart, tb_choice_jong_no, tb_bookmark)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_cc_cart ===========
CREATE TABLE tb_cc_cart (
  seq BIGINT,
  user_id varchar(20),
  leccode varchar(30),
  kind_type varchar(1),
  rsc_id varchar(30),
  rsc_type varchar(1),
  movie_type varchar(2),
  regdate date,
  reprice BIGINT,
  package_period BIGINT,
  sdate varchar(50),
  edate varchar(50),
  book_count BIGINT,
  orderno varchar(20)
);


-- =========== tb_cc_j_cart ===========
CREATE TABLE tb_cc_j_cart (
  seq BIGINT,
  leccode varchar(30),
  mst_leccode varchar(30),
  update_id varchar(30),
  reg_dt date,
  price BIGINT,
  kind_type varchar(1)
);


-- =========== tb_choice_jong_no ===========
CREATE TABLE tb_choice_jong_no (
  seq BIGINT,
  leccode varchar(30),
  no BIGINT,
  category_cd varchar(100)
);


-- =========== tb_bookmark ===========
CREATE TABLE tb_bookmark (
  user_id varchar(100),
  orderno varchar(30),
  package_no varchar(30),
  lecture_no varchar(30),
  movie_no varchar(30),
  bookmark_no BIGINT,
  bookmark_name varchar(4000),
  bookmark_time BIGINT,
  bookmark_speed varchar(50),
  reg_dt date
);


