-- ============================================
-- V14__legacy_tb_board_inquiry.sql
-- 윌비스 게시판/문의 (legacy + 신규)
-- 대상 테이블: 15개 (tb_board, tb_board2, tb_board_category_info, tb_board_comment, tb_board_cs...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_board ===========
CREATE TABLE tb_board (
  board_mng_seq varchar(20),
  open_yn varchar(1),
  subject varchar(200),
  content BYTEA,
  file_path varchar(100),
  file_name varchar(100),
  real_file_name varchar(100),
  notice_top_yn varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  hits BIGINT,
  createname varchar(30),
  answer BYTEA,
  thumbnail_file_path varchar(100),
  thumbnail_file_name varchar(100),
  thumbnail_file_real_name varchar(100),
  is_use varchar(1),
  recommend varchar(1),
  board_seq3 BIGINT,
  exam_type varchar(1),
  exam_area varchar(50),
  exam_cate varchar(1),
  exam_sub varchar(50),
  category_code varchar(100),
  board_seq varchar(20),
  parent_board_seq varchar(20),
  prof_id varchar(30),
  board_type varchar(2),
  mockcode varchar(20),
  divice_type varchar(1)
);


-- =========== tb_board2 ===========
CREATE TABLE tb_board2 (
  board_mng_seq varchar(20),
  board_seq varchar(20),
  open_yn varchar(1),
  subject varchar(200),
  content BYTEA,
  file_path varchar(100),
  file_name varchar(100),
  real_file_name varchar(100),
  parent_board_seq varchar(20),
  notice_top_yn varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  hits BIGINT,
  createname varchar(30),
  answer BYTEA,
  thumbnail_file_path varchar(100),
  thumbnail_file_name varchar(100),
  thumbnail_file_real_name varchar(100),
  issue varchar(1),
  recommend varchar(1)
);


-- =========== tb_board_category_info ===========
CREATE TABLE tb_board_category_info (
  board_mng_seq varchar(20),
  board_seq varchar(20),
  category_code varchar(20)
);


-- =========== tb_board_comment ===========
CREATE TABLE tb_board_comment (
  seq BIGINT,
  board_mng_seq varchar(20),
  board_seq varchar(20),
  user_id varchar(30),
  user_name varchar(50),
  title varchar(200),
  content varchar(4000),
  choice_point varchar(1),
  reg_dt date
);


-- =========== tb_board_cs ===========
CREATE TABLE tb_board_cs (
  board_mng_seq varchar(20),
  board_seq varchar(20),
  cs_div varchar(20),
  cs_kind varchar(20),
  open_yn varchar(1),
  subject varchar(200),
  content BYTEA,
  file_path varchar(100),
  file_name varchar(100),
  real_file_name varchar(100),
  parent_board_seq varchar(20),
  notice_top_yn varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  hits BIGINT,
  createname varchar(30),
  answer BYTEA,
  thumbnail_file_path varchar(100),
  thumbnail_file_name varchar(100),
  thumbnail_file_real_name varchar(100),
  issue varchar(1),
  recommend varchar(1),
  counselor_id varchar(30),
  action_yn varchar(20)
);


-- =========== tb_board_file ===========
CREATE TABLE tb_board_file (
  board_mng_seq varchar(20),
  board_seq varchar(20),
  file_no varchar(20),
  file_name varchar(100),
  file_path varchar(100),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date,
  parent_board_seq varchar(20)
);


-- =========== tb_board_mng ===========
CREATE TABLE tb_board_mng (
  onoff_div varchar(1),
  board_mng_seq varchar(20),
  board_mng_name varchar(200),
  board_mng_type varchar(20),
  attach_file_yn varchar(1),
  open_yn varchar(1),
  reply_yn varchar(1),
  is_use varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_board_voting ===========
CREATE TABLE tb_board_voting (
  board_mng_seq varchar(20),
  board_seq varchar(20),
  reg_id varchar(30),
  istype varchar(1),
  voting varchar(1),
  reg_dt date
);


-- =========== tb_inquiry ===========
CREATE TABLE tb_inquiry (
  inquiry_id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  user_id varchar(50) NOT NULL,
  user_name varchar(50) NOT NULL,
  title varchar(300) NOT NULL,
  body TEXT NOT NULL,
  inquiry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  predicted_category varchar(30),
  predicted_confidence decimal(5,4),
  classified_by_model varchar(50),
  classified_at TIMESTAMP,
  actual_category varchar(30),
  assigned_to varchar(50),
  reroute_count INTEGER NOT NULL DEFAULT 0,
  answer_body TEXT,
  answered_by varchar(50),
  answered_at TIMESTAMP,
  resolution_state varchar(20) NOT NULL DEFAULT 'OPEN',
  user_satisfaction SMALLINT,
  reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upd_dt TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  is_deleted char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (inquiry_id)
);

CREATE INDEX ix_tb_inquiry_user ON tb_inquiry (user_id, inquiry_date);
CREATE INDEX ix_tb_inquiry_state ON tb_inquiry (resolution_state, inquiry_date);
CREATE INDEX ix_tb_inquiry_predicted ON tb_inquiry (predicted_category, classified_at);
CREATE INDEX ix_tb_inquiry_actual ON tb_inquiry (actual_category, reg_dt);
CREATE INDEX ix_tb_inquiry_assigned ON tb_inquiry (assigned_to, resolution_state);
CREATE INDEX ix_tb_inquiry_inquiry_date ON tb_inquiry (inquiry_date);
COMMENT ON COLUMN tb_inquiry.predicted_category IS 'ACADEMIC|ORDER|SYSTEM|OTHER';
COMMENT ON COLUMN tb_inquiry.predicted_confidence IS '0.0000 ~ 1.0000';
COMMENT ON COLUMN tb_inquiry.classified_by_model IS 'qwen2.5:7b@v3 식 모델 버전';
COMMENT ON COLUMN tb_inquiry.actual_category IS '운영자 확정 카테고리';
COMMENT ON COLUMN tb_inquiry.assigned_to IS '담당자 user_id';
COMMENT ON COLUMN tb_inquiry.resolution_state IS 'OPEN|ANSWERED|RESOLVED|CLOSED';
COMMENT ON COLUMN tb_inquiry.user_satisfaction IS '1-5 별점';

-- =========== tb_inquiry_file ===========
CREATE TABLE tb_inquiry_file (
  file_seq BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  inquiry_id BIGINT NOT NULL,
  file_name varchar(300) NOT NULL,
  stored_path varchar(500) NOT NULL,
  mime_type varchar(100),
  size_bytes BIGINT,
  upload_target varchar(20) NOT NULL DEFAULT 'QUESTION',
  reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (file_seq)
);

CREATE INDEX ix_tb_inquiry_file_inquiry ON tb_inquiry_file (inquiry_id, upload_target);
COMMENT ON COLUMN tb_inquiry_file.file_name IS '원본 파일명';
COMMENT ON COLUMN tb_inquiry_file.stored_path IS '저장 경로 (서버 디스크 또는 S3 key)';
COMMENT ON COLUMN tb_inquiry_file.upload_target IS 'QUESTION (사용자 첨부) | ANSWER (운영자 첨부)';

-- =========== tb_inquiry_train ===========
CREATE TABLE tb_inquiry_train (
  inquiry_id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  source_table varchar(20) NOT NULL DEFAULT 'TB_BOARD_CS',
  source_id varchar(50),
  legacy_board_seq varchar(20),
  legacy_cs_div varchar(20),
  legacy_cs_kind varchar(20),
  inquiry_user_id varchar(50) NOT NULL,
  inquiry_name varchar(50) NOT NULL,
  inquiry_title varchar(300) NOT NULL,
  inquiry_body TEXT NOT NULL,
  inquiry_date TIMESTAMP NOT NULL,
  predicted_category varchar(30),
  predicted_confidence decimal(5,4),
  classified_by_model varchar(50),
  classified_at TIMESTAMP,
  actual_category varchar(30),
  assigned_to varchar(50),
  reroute_count INTEGER NOT NULL DEFAULT 0,
  answer_body TEXT,
  answered_by varchar(50),
  answered_at TIMESTAMP,
  resolution_state varchar(20) NOT NULL DEFAULT 'OPEN',
  user_satisfaction SMALLINT,
  reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upd_dt TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  is_deleted char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (inquiry_id)
);

CREATE UNIQUE INDEX ux_tb_inquiry_train_legacy ON tb_inquiry_train (legacy_board_seq);
CREATE INDEX ix_tb_inquiry_train_predicted ON tb_inquiry_train (predicted_category, classified_at);
CREATE INDEX ix_tb_inquiry_train_actual ON tb_inquiry_train (actual_category, reg_dt);
CREATE INDEX ix_tb_inquiry_train_state ON tb_inquiry_train (resolution_state);
CREATE INDEX ix_tb_inquiry_train_assigned ON tb_inquiry_train (assigned_to, resolution_state);
CREATE INDEX ix_tb_inquiry_train_inquiry_date ON tb_inquiry_train (inquiry_date);
CREATE INDEX ix_tb_inquiry_train_user ON tb_inquiry_train (inquiry_user_id);
CREATE INDEX ix_tb_inquiry_train_source ON tb_inquiry_train (source_table, source_id);
COMMENT ON COLUMN tb_inquiry_train.source_table IS '원본 테이블 — TB_BOARD_CS | tb_inquiry';
COMMENT ON COLUMN tb_inquiry_train.source_id IS '원본 PK (TB_BOARD_CS.BOARD_SEQ 또는 tb_inquiry.inquiry_id)';
COMMENT ON COLUMN tb_inquiry_train.legacy_board_seq IS 'tb_board_cs.BOARD_SEQ';
COMMENT ON COLUMN tb_inquiry_train.legacy_cs_div IS 'tb_board_cs.CS_DIV — CSCOUNSEL/CSREFUND 등';
COMMENT ON COLUMN tb_inquiry_train.legacy_cs_kind IS 'tb_board_cs.CS_KIND — CSC120/CSR220 등';
COMMENT ON COLUMN tb_inquiry_train.inquiry_user_id IS '마스킹된 usr_{hash}';
COMMENT ON COLUMN tb_inquiry_train.inquiry_name IS 'Faker 한국어 이름';
COMMENT ON COLUMN tb_inquiry_train.inquiry_body IS '본문 (정규식 PII 치환 후)';
COMMENT ON COLUMN tb_inquiry_train.predicted_category IS 'ACADEMIC|ORDER|SYSTEM|OTHER';
COMMENT ON COLUMN tb_inquiry_train.predicted_confidence IS '0.0000 ~ 1.0000';
COMMENT ON COLUMN tb_inquiry_train.classified_by_model IS 'ex: qwen2.5:7b';
COMMENT ON COLUMN tb_inquiry_train.assigned_to IS '담당자 user_id';
COMMENT ON COLUMN tb_inquiry_train.resolution_state IS 'OPEN|ANSWERED|RESOLVED|CLOSED';
COMMENT ON COLUMN tb_inquiry_train.user_satisfaction IS '1-5 별점';

-- =========== tb_inquiry_analysis ===========
CREATE TABLE tb_inquiry_analysis (
  analysis_seq BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  inquiry_id BIGINT NOT NULL,
  model_name varchar(50) NOT NULL,
  model_version varchar(50),
  prompt_template varchar(50) NOT NULL,
  raw_output text,
  parsed_category varchar(30),
  confidence decimal(5,4),
  latency_ms INTEGER,
  error_msg text,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_seq)
);

CREATE INDEX ix_tb_inquiry_analysis_cs_time ON tb_inquiry_analysis (inquiry_id, created_at);
CREATE INDEX ix_tb_inquiry_analysis_model ON tb_inquiry_analysis (model_name, created_at);
COMMENT ON COLUMN tb_inquiry_analysis.model_name IS 'qwen2.5:7b 등';
COMMENT ON COLUMN tb_inquiry_analysis.model_version IS 'Ollama digest';
COMMENT ON COLUMN tb_inquiry_analysis.prompt_template IS 'v1, v2 ... few-shot 버전';
COMMENT ON COLUMN tb_inquiry_analysis.raw_output IS 'LLM 원 응답 (감사)';

-- =========== tb_inquiry_routing_log ===========
CREATE TABLE tb_inquiry_routing_log (
  log_seq BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  inquiry_id BIGINT NOT NULL,
  from_category varchar(30),
  to_category varchar(30) NOT NULL,
  from_user varchar(50),
  to_user varchar(50) NOT NULL,
  reason varchar(500),
  changed_by varchar(50) NOT NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_ai_error char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (log_seq)
);

CREATE INDEX ix_tb_inquiry_routing_log_cs ON tb_inquiry_routing_log (inquiry_id);
CREATE INDEX ix_tb_inquiry_routing_log_learning ON tb_inquiry_routing_log (is_ai_error, changed_at);
COMMENT ON COLUMN tb_inquiry_routing_log.from_category IS 'AI 최초 분류 또는 직전 할당';
COMMENT ON COLUMN tb_inquiry_routing_log.is_ai_error IS 'Y=AI 오분류로 간주 → few-shot 학습 셋 포함';

-- =========== tb_inquiry_stats_monthly ===========
CREATE TABLE tb_inquiry_stats_monthly (
  stat_ym char(7) NOT NULL,
  category varchar(30) NOT NULL,
  total_count INTEGER NOT NULL DEFAULT 0,
  resolved_count INTEGER NOT NULL DEFAULT 0,
  avg_response_hours decimal(8,2),
  avg_satisfaction decimal(3,2),
  ai_correct_rate decimal(5,4),
  mom_delta_pct decimal(6,2),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  PRIMARY KEY (stat_ym, category)
);

COMMENT ON COLUMN tb_inquiry_stats_monthly.stat_ym IS 'YYYY-MM';
COMMENT ON COLUMN tb_inquiry_stats_monthly.avg_satisfaction IS '1-5';
COMMENT ON COLUMN tb_inquiry_stats_monthly.ai_correct_rate IS 'is_ai_error=N 비율';
COMMENT ON COLUMN tb_inquiry_stats_monthly.mom_delta_pct IS '전월 대비 변화율';

-- =========== tb_inquiry_embedding ===========
CREATE TABLE tb_inquiry_embedding (
  inquiry_id BIGINT NOT NULL,
  model_name varchar(50) NOT NULL,
  dim INTEGER NOT NULL,
  embedding BYTEA NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (inquiry_id, model_name)
);

CREATE INDEX ix_tb_inquiry_embedding_created ON tb_inquiry_embedding (created_at);
COMMENT ON COLUMN tb_inquiry_embedding.model_name IS 'nomic-embed-text 등';
COMMENT ON COLUMN tb_inquiry_embedding.embedding IS 'float32 array, little-endian';


-- ============================================
-- ON UPDATE CURRENT_TIMESTAMP 트리거
-- ============================================
-- 공용 트리거 함수 (한 번만 정의 — 첫 번째 V 에서만 CREATE)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_upd_dt_now') THEN
        EXECUTE $func$
            CREATE FUNCTION set_upd_dt_now() RETURNS trigger AS $body$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    -- 컬럼명이 upd_dt 또는 updated_at 인 경우 모두 처리
                    BEGIN
                        NEW.upd_dt := CURRENT_TIMESTAMP;
                    EXCEPTION WHEN OTHERS THEN
                        BEGIN
                            NEW.updated_at := CURRENT_TIMESTAMP;
                        EXCEPTION WHEN OTHERS THEN
                            NULL;
                        END;
                    END;
                END IF;
                RETURN NEW;
            END;
            $body$ LANGUAGE plpgsql;
        $func$;
    END IF;
END $$;


DROP TRIGGER IF EXISTS trg_tb_inquiry_upd_dt ON tb_inquiry;
CREATE TRIGGER trg_tb_inquiry_upd_dt BEFORE UPDATE ON tb_inquiry
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();

DROP TRIGGER IF EXISTS trg_tb_inquiry_train_upd_dt ON tb_inquiry_train;
CREATE TRIGGER trg_tb_inquiry_train_upd_dt BEFORE UPDATE ON tb_inquiry_train
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();

DROP TRIGGER IF EXISTS trg_tb_inquiry_stats_monthly_upd_dt ON tb_inquiry_stats_monthly;
CREATE TRIGGER trg_tb_inquiry_stats_monthly_upd_dt BEFORE UPDATE ON tb_inquiry_stats_monthly
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();
