-- ============================================
-- V15__legacy_tb_event_banner_popup.sql
-- 윌비스 이벤트/배너/팝업
-- 대상 테이블: 8개 (tb_event_info, tb_event_file, tb_event_option1, tb_event_option2, tb_event_result...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_event_info ===========
CREATE TABLE tb_event_info (
  event_no varchar(20),
  onoff_div varchar(1),
  category_code varchar(30),
  notice_gubun varchar(10),
  open_yn varchar(1),
  member_gubun varchar(1),
  hit BIGINT,
  start_date varchar(8),
  start_time varchar(2),
  end_date varchar(8),
  end_time varchar(2),
  title varchar(500),
  contents_text BYTEA,
  contents_img varchar(100),
  list_thumbnail varchar(100),
  issue_thumbnail varchar(100),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date,
  option1_yn varchar(1),
  option2_yn varchar(1)
);


-- =========== tb_event_file ===========
CREATE TABLE tb_event_file (
  event_no varchar(20),
  file_no varchar(20),
  file_name varchar(100),
  file_path varchar(100),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_event_option1 ===========
CREATE TABLE tb_event_option1 (
  event_no varchar(20),
  option_no varchar(20),
  option_name varchar(2000),
  people_gubun varchar(1),
  people_cnt BIGINT,
  multi_select_yn varchar(1),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_event_option2 ===========
CREATE TABLE tb_event_option2 (
  event_no varchar(20),
  no BIGINT,
  user_id varchar(30),
  user_nm varchar(50),
  txt varchar(4000),
  reg_dt date
);


-- =========== tb_event_result ===========
CREATE TABLE tb_event_result (
  event_no varchar(20),
  option_no varchar(20),
  user_id varchar(30),
  user_name varchar(50),
  phone_no varchar(20),
  email varchar(50),
  reg_dt date
);


-- =========== tb_banner ===========
CREATE TABLE tb_banner (
  seq BIGINT,
  onoff_div varchar(1),
  screen_gubun varchar(1),
  category_cd varchar(100),
  banner_no BIGINT,
  banner_title varchar(100),
  banner_image varchar(100),
  banner_thumbnail_image varchar(100),
  banner_link varchar(1000),
  banner_link_target varchar(1),
  open_startdate date,
  open_enddate date,
  is_use varchar(1),
  view_count BIGINT,
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  rol_idx BIGINT,
  banner_typ varchar(1)
);


-- =========== tb_banner_item ===========
CREATE TABLE tb_banner_item (
  seq BIGINT,
  p_seq BIGINT,
  rol_idx BIGINT,
  banner_subtitle varchar(100),
  banner_note varchar(1000),
  banner_image varchar(100),
  banner_thumbnail_image varchar(100),
  banner_link varchar(1000),
  banner_link_target varchar(1),
  banner_sdt date,
  banner_edt date,
  click_cnt BIGINT,
  is_use varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_popup_info ===========
CREATE TABLE tb_popup_info (
  no varchar(20),
  onoff_div varchar(1),
  category_code varchar(30),
  start_date varchar(8),
  start_time varchar(2),
  end_date varchar(8),
  end_time varchar(2),
  open_yn varchar(1),
  hit BIGINT,
  title varchar(500),
  popup_img varchar(100),
  thumbnail varchar(100),
  link_addr varchar(500),
  link_target varchar(10),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date,
  popup_img_nm varchar(100),
  thumbnail_nm varchar(100)
);


