-- ============================================
-- V16__legacy_tb_sg_menu_site.sql
-- 윌비스 사이트/메뉴 (sg_*)
-- 대상 테이블: 4개 (tb_sg_site, tb_sg_site_menu, tb_sg_menu_mst, tb_sg_menu_mst2)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_sg_site ===========
CREATE TABLE tb_sg_site (
  onoff_div varchar(1),
  site_id varchar(20),
  site_nm varchar(50),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_sg_site_menu ===========
CREATE TABLE tb_sg_site_menu (
  site_id varchar(20),
  menu_id varchar(20),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_sg_menu_mst ===========
CREATE TABLE tb_sg_menu_mst (
  onoff_div varchar(1),
  menu_id varchar(20),
  menu_nm varchar(50),
  menu_seq varchar(100),
  menu_url varchar(150),
  p_menuid varchar(20),
  isuse varchar(1),
  target varchar(20),
  menu_info varchar(255),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_sg_menu_mst2 ===========
CREATE TABLE tb_sg_menu_mst2 (
  onoff_div varchar(1),
  menu_id varchar(20),
  menu_nm varchar(50),
  menu_seq varchar(100),
  menu_url varchar(250),
  p_menuid varchar(20),
  isuse varchar(1),
  target varchar(20),
  menu_info varchar(255),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  code varchar(3),
  top_img_url varchar(200),
  left_img_url varchar(200),
  titl_img_url varchar(200),
  subtitl_img_url varchar(200),
  pblc_yn varchar(1)
);


