-- ============================================
-- V17__legacy_tb_tm_message.sql
-- 윌비스 메시지/쿠폰 (tm_*)
-- 대상 테이블: 3개 (tb_tm_board, tb_tm_coupon, tb_tm_mycoupon)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_tm_board ===========
CREATE TABLE tb_tm_board (
  idx BIGINT,
  voccode varchar(20),
  dutycode varchar(20),
  content varchar(4000),
  requserid varchar(30),
  requsername varchar(30),
  reguserid varchar(30),
  regusername varchar(30),
  regdate date NOT NULL,
  upddate date
);


-- =========== tb_tm_coupon ===========
CREATE TABLE tb_tm_coupon (
  ccode varchar(20),
  cname varchar(150),
  ccontent varchar(1000),
  regdate date NOT NULL,
  regtype varchar(1),
  regprice BIGINT,
  expdates date,
  expdatee date NOT NULL,
  expday BIGINT,
  tclass varchar(20),
  tclasscat BIGINT,
  pub_coupon_gubun varchar(2),
  term varchar(2),
  dan_jong varchar(1),
  dan_menu varchar(10),
  subject varchar(50),
  teacher varchar(30),
  price BIGINT,
  add_flag varchar(1)
);


-- =========== tb_tm_mycoupon ===========
CREATE TABLE tb_tm_mycoupon (
  idx BIGINT,
  ccode varchar(20),
  userid varchar(30),
  regdate date NOT NULL,
  expdates date NOT NULL,
  expdatee date NOT NULL,
  orderno varchar(20),
  orderdate date,
  orderflag varchar(1),
  reg_id varchar(20),
  event_no BIGINT
);


