-- ============================================
-- V18__legacy_tb_test.sql
-- 윌비스 시험/모의고사 (t* prefix, exam_* 와 별도)
-- 대상 테이블: 18개 (tb_top_mst, tb_titem, tb_titempool, tb_tcommoncode, tb_texamidseq...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_top_mst ===========
CREATE TABLE tb_top_mst (
  seq BIGINT,
  mstcode varchar(30),
  subject_teacher varchar(30),
  subject_title varchar(1000),
  subject_sjt_cd varchar(50),
  subject_desc BYTEA,
  subject_memo BYTEA,
  subject_period BIGINT,
  lec_schedule varchar(50),
  subject_off_open_year varchar(4),
  subject_off_open_month varchar(2),
  subject_off_open_day varchar(2),
  subject_price BIGINT,
  subject_option varchar(1000),
  subject_vod_default_path varchar(800),
  subject_mp4_default_path varchar(800),
  subject_pmp_default_path varchar(800),
  mst_use_yn varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_titem ===========
CREATE TABLE tb_titem (
  itemid BIGINT,
  examyear BIGINT,
  examround BIGINT,
  subject_cd varchar(20),
  profcode varchar(20),
  entrynum BIGINT,
  questionnum BIGINT,
  questionregistrationoption BIGINT,
  openstate BIGINT,
  deleteflag BIGINT,
  reg_id varchar(20),
  reg_dt date NOT NULL,
  upd_id varchar(20),
  upd_dt date,
  fee_prof varchar(5),
  code_nm varchar(150),
  questionfid BIGINT,
  answerfid BIGINT
);


-- =========== tb_titempool ===========
CREATE TABLE tb_titempool (
  questionnumber BIGINT,
  itemid BIGINT,
  question varchar(500),
  questionfileid BIGINT,
  answerexplain varchar(500),
  answerexplainfileid BIGINT,
  answernumber varchar(200),
  questionrange BIGINT,
  leveldifficulty BIGINT,
  questionpattern varchar(20),
  useflag BIGINT,
  referenceexamyear BIGINT,
  referenceexamround BIGINT,
  referenceexamquestionnumber BIGINT,
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_tcommoncode ===========
CREATE TABLE tb_tcommoncode (
  id BIGINT,
  code varchar(20),
  parentcode varchar(20),
  codename varchar(40),
  codedesc varchar(100),
  codevalue varchar(20),
  coderank BIGINT,
  useflag BIGINT,
  reg_id varchar(20),
  reg_dt date,
  upd_id varchar(20),
  upd_dt date
);


-- =========== tb_texamidseq ===========
CREATE TABLE tb_texamidseq (
  gubun varchar(2),
  idtype varchar(10),
  seq BIGINT
);


-- =========== tb_texamineeanswer ===========
CREATE TABLE tb_texamineeanswer (
  id BIGINT,
  identyid varchar(20),
  itemid BIGINT,
  questionnumber BIGINT,
  mockcode varchar(20),
  answernumber varchar(200),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date,
  correctyn varchar(2)
);


-- =========== tb_tboardtestclass ===========
CREATE TABLE tb_tboardtestclass (
  bcontentid BIGINT,
  classcode varchar(20)
);


-- =========== tb_tboardtestenv ===========
CREATE TABLE tb_tboardtestenv (
  boardenvid BIGINT,
  boardtitle varchar(50),
  description varchar(200),
  boardtype varchar(20),
  hasreply BIGINT,
  hascomment BIGINT,
  reg_id varchar(20),
  reg_dt date,
  upd_id varchar(20),
  upd_dt date,
  leveluser BIGINT,
  levelprof BIGINT,
  leveladmin BIGINT
);


-- =========== tb_tattachfile ===========
CREATE TABLE tb_tattachfile (
  attachfileid BIGINT,
  filename varchar(250),
  filepath varchar(250),
  filesize varchar(11),
  regdate date
);


-- =========== tb_tapprovals ===========
CREATE TABLE tb_tapprovals (
  tid varchar(30),
  identyid varchar(20),
  orderno varchar(20),
  paymenttargetamount BIGINT,
  paymentamount BIGINT,
  adddiscountratio BIGINT,
  adddiscountamount BIGINT,
  adddiscountreason varchar(100),
  paymentduedate varchar(20),
  paymentstate BIGINT,
  paymenttype BIGINT,
  cardkind varchar(20),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_tsubjectarea ===========
CREATE TABLE tb_tsubjectarea (
  id BIGINT,
  subject_cd varchar(20),
  subjectarea varchar(80),
  areaorder BIGINT,
  useflag BIGINT,
  reg_id varchar(30),
  reg_dt varchar(20),
  upd_id varchar(30),
  upd_dt varchar(20)
);


-- =========== tb_tccsrssubjectinfo ===========
CREATE TABLE tb_tccsrssubjectinfo (
  id BIGINT,
  classcode varchar(20),
  classseriescode varchar(20),
  subject_cd varchar(20),
  subjecttypedivision BIGINT,
  subjectorder BIGINT,
  reg_id varchar(20),
  reg_dt date,
  upd_id varchar(20),
  upd_dt date
);


-- =========== tb_tuserchoicesubject ===========
CREATE TABLE tb_tuserchoicesubject (
  id BIGINT,
  itemid BIGINT,
  orderno varchar(20),
  identyid varchar(20),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date,
  examstatus BIGINT,
  subjectorder BIGINT,
  subjecttypedivision BIGINT,
  examsstarttime date
);


-- =========== tb_twronganswernote ===========
CREATE TABLE tb_twronganswernote (
  id BIGINT,
  identyid varchar(20),
  itemid BIGINT,
  questionnumber BIGINT,
  note varchar(500),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date,
  mockcode varchar(20)
);


-- =========== tb_tmockregistration ===========
CREATE TABLE tb_tmockregistration (
  id BIGINT,
  mockcode varchar(20),
  mockname varchar(50),
  examyear BIGINT,
  examround BIGINT,
  offclosepersonnumber BIGINT,
  classcode varchar(20),
  examstarttime varchar(20),
  examendtime varchar(20),
  examperiod BIGINT,
  examtime BIGINT,
  receiptstarttime varchar(20),
  receiptendtime varchar(20),
  examcost BIGINT,
  discountratio BIGINT,
  saleamounts BIGINT,
  useflag varchar(1),
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date,
  isexamtypeon BIGINT,
  isexamtypeoff BIGINT,
  examperiodtype BIGINT
);


-- =========== tb_tmocksubject ===========
CREATE TABLE tb_tmocksubject (
  id BIGINT,
  mockcode varchar(20),
  subject_cd varchar(20),
  itemid BIGINT,
  subjectorder BIGINT,
  subjecttypedivision BIGINT,
  subjectperiod BIGINT,
  useflag BIGINT,
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date
);


-- =========== tb_tmockgrade ===========
CREATE TABLE tb_tmockgrade (
  id BIGINT,
  identyid varchar(20),
  mockcode varchar(20),
  subject_cd varchar(20),
  classcode varchar(20),
  classseriescode varchar(20),
  origingrade BIGINT,
  adjustgrade BIGINT,
  reg_id varchar(30),
  reg_dt date,
  upd_id varchar(30),
  upd_dt date,
  itemid BIGINT
);


-- =========== tb_tmockclsclsseries ===========
CREATE TABLE tb_tmockclsclsseries (
  id BIGINT,
  mockcode varchar(20),
  classseriescode varchar(20),
  reg_id varchar(30),
  reg_dt date NOT NULL,
  upd_id varchar(30),
  upd_dt date
);


