-- ============================================
-- V19__legacy_tb_misc.sql
-- 윌비스 기타 (우편번호/마일리지/통계/공통)
-- 대상 테이블: 14개 (tb_zipcode, tb_zipcode_new, tb_pmp_downlog, tb_mileage_history, tb_renew_history...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_zipcode ===========
CREATE TABLE tb_zipcode (
  zipcd varchar(7),
  sido varchar(500),
  gugun varchar(500),
  dong varchar(500),
  ri varchar(500),
  "do" varchar(100),
  bunji varchar(500),
  juso varchar(500)
);


-- =========== tb_zipcode_new ===========
CREATE TABLE tb_zipcode_new (
  zipcd varchar(7),
  sido varchar(500),
  gugun varchar(500),
  dong varchar(500),
  ri varchar(500),
  "do" varchar(500),
  bunji varchar(500),
  juso varchar(500)
);


-- =========== tb_pmp_downlog ===========
CREATE TABLE tb_pmp_downlog (
  idx BIGINT,
  userid varchar(30),
  contentid varchar(20),
  downloginfo varchar(60),
  pmp_regdate date
);


-- =========== tb_mileage_history ===========
CREATE TABLE tb_mileage_history (
  idx BIGINT,
  userid varchar(30),
  point BIGINT,
  orderno varchar(20),
  mgntno varchar(20),
  regdate date,
  comment1 varchar(200),
  manager varchar(20),
  site varchar(50)
);


-- =========== tb_renew_history ===========
CREATE TABLE tb_renew_history (
  orderno varchar(20),
  old_package_no varchar(20),
  new_package_no varchar(20),
  regdate date
);


-- =========== tb_comment ===========
CREATE TABLE tb_comment (
  seq BIGINT,
  leccode varchar(30),
  user_id varchar(30),
  user_name varchar(50),
  content varchar(4000),
  choice_point varchar(1),
  reg_dt date,
  title varchar(200)
);


-- =========== tb_dday ===========
CREATE TABLE tb_dday (
  dday_idx BIGINT,
  user_id varchar(20),
  dday_type varchar(1),
  dday_category varchar(20),
  dday_name varchar(200),
  dday_date varchar(10),
  regdate date NOT NULL,
  dday_link BIGINT,
  dday_active varchar(1)
);


-- =========== tb_discount ===========
CREATE TABLE tb_discount (
  lec_menu1 varchar(10),
  lec_menu2 varchar(10),
  start_event_date date NOT NULL,
  end_event_date date NOT NULL,
  event_count BIGINT,
  event_percent BIGINT
);


-- =========== tb_note_send_info ===========
CREATE TABLE tb_note_send_info (
  noteid BIGINT,
  from_userid varchar(30),
  send_dt date,
  send_id varchar(30),
  cont varchar(4000),
  read_yn varchar(1)
);


-- =========== tb_stat_prf ===========
CREATE TABLE tb_stat_prf (
  s_year varchar(4),
  s_month varchar(2),
  s_type varchar(2),
  prf_id varchar(20),
  sale_cnt BIGINT,
  refund_cnt BIGINT,
  sale_sum BIGINT,
  refund_sum BIGINT
);


-- =========== tb_ba_config_cd ===========
CREATE TABLE tb_ba_config_cd (
  sys_cd varchar(20),
  code_no BIGINT,
  sys_nm varchar(100),
  code_nm varchar(100),
  code_val varchar(20),
  code_info varchar(1000),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  code_cd varchar(20)
);


-- =========== tb_common_password ===========
CREATE TABLE tb_common_password (
  common_pwd varchar(100),
  pwd_desc varchar(100)
);


-- =========== tb_danintcount ===========
CREATE TABLE tb_danintcount (
  orderno varchar(20),
  dan_int_count BIGINT,
  real_cartsum BIGINT,
  regdate date
);


-- =========== tb_danpint ===========
CREATE TABLE tb_danpint (
  orderno varchar(20),
  dan_point BIGINT,
  real_cartsum BIGINT,
  regdate date,
  book_point BIGINT,
  user_id varchar(20)
);


