-- ============================================
-- V20__gosi_master.sql
-- 고시 마스터/과목 (9종)
-- 대상 테이블: 9개 (gosi_mst, gosi_cod, gosi_subject, gosi_sbj_mst, gosi_area_mst...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== gosi_mst ===========
CREATE TABLE gosi_mst (
  gosi_cd varchar(20),
  gosi_nm varchar(100)
);


-- =========== gosi_cod ===========
CREATE TABLE gosi_cod (
  gosi_type varchar(2),
  gosi_type_nm varchar(100)
);


-- =========== gosi_subject ===========
CREATE TABLE gosi_subject (
  gosi_type varchar(2),
  gosi_subject_cd varchar(3),
  gosi_subject_type varchar(1),
  gosi_subject_nm varchar(100)
);


-- =========== gosi_sbj_mst ===========
CREATE TABLE gosi_sbj_mst (
  gosi_cd varchar(20),
  sbj_type varchar(20),
  subject_cd varchar(20),
  subject_nm varchar(20),
  req_usr_num BIGINT,
  sum_point BIGINT,
  avr_point BIGINT,
  sdv BIGINT,
  avr_3_point BIGINT,
  avr_10_point BIGINT
);


-- =========== gosi_area_mst ===========
CREATE TABLE gosi_area_mst (
  gosi_type varchar(2),
  gosi_area varchar(1),
  gosi_area_nm varchar(100),
  gosi_area_full_nm varchar(200),
  req_num varchar(10),
  use_num varchar(20),
  gosi_cmp_stat varchar(20),
  pass_2014 varchar(10),
  pass_2015_s varchar(10),
  pass_2015_e varchar(10)
);


-- =========== gosi_pass_mst ===========
CREATE TABLE gosi_pass_mst (
  gosi_cd varchar(20),
  subject_cd varchar(20),
  exam_type varchar(1),
  item_no BIGINT,
  pass_ans BIGINT
);


-- =========== gosi_pass_sta ===========
CREATE TABLE gosi_pass_sta (
  gosi_cd varchar(20),
  gosi_type varchar(10),
  pass_point BIGINT
);


-- =========== gosi_stat_mst ===========
CREATE TABLE gosi_stat_mst (
  gosi_cd varchar(20),
  gosi_type varchar(20),
  gosi_area varchar(20),
  gosi_subject_cd varchar(20),
  gosi_subjec_nm varchar(20),
  gosi_user_num BIGINT,
  gosi_avr_point BIGINT,
  gosi_3_point BIGINT,
  gosi_10_point BIGINT,
  gosi_adj_avr_point BIGINT,
  gosi_adj_3_point BIGINT,
  gosi_adj_10_point BIGINT
);


-- =========== gosi_vod ===========
CREATE TABLE gosi_vod (
  gosi_cd varchar(20),
  prf_id varchar(20),
  prf_nm varchar(50),
  sbj_nm varchar(200),
  title varchar(200),
  vod_url varchar(500),
  file_url varchar(500),
  isuse varchar(1),
  idx BIGINT
);


