-- ============================================
-- V22__counsel.sql
-- 상담 (3종)
-- 대상 테이블: 3개 (counsel_rst, counsel_sch, counsel_time)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== counsel_rst ===========
CREATE TABLE counsel_rst (
  sch_day varchar(10),
  ts_idx BIGINT,
  user_id varchar(20),
  reserve varchar(1),
  reg_dt date,
  user_birthday varchar(10),
  user_nm varchar(20),
  user_phone varchar(20),
  user_email varchar(100),
  user_category varchar(50),
  user_code1 varchar(100),
  user_code2 varchar(100),
  user_period varchar(1),
  user_subject varchar(100),
  user_lec varchar(200),
  user_comments varchar(2000),
  cancel_date date,
  user_area varchar(100)
);


-- =========== counsel_sch ===========
CREATE TABLE counsel_sch (
  sch_day varchar(10),
  ts_idx BIGINT,
  max_usr BIGINT,
  req_cnt BIGINT,
  isuse varchar(1),
  req_type varchar(1),
  cat_cd varchar(20)
);


-- =========== counsel_time ===========
CREATE TABLE counsel_time (
  idx BIGINT,
  time_set varchar(100),
  isuse varchar(1)
);


