-- ============================================
-- V23__coop.sql
-- 협력사 쿠폰 (4종)
-- 대상 테이블: 4개 (coop_mst, coop_coupon, coop_coupon_mst, cop_seq)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== coop_mst ===========
CREATE TABLE coop_mst (
  coop_cd varchar(20),
  coop_nm varchar(50),
  reg_dt date,
  discount_per BIGINT
);


-- =========== coop_coupon ===========
CREATE TABLE coop_coupon (
  c_cd varchar(16),
  coop_cd varchar(10),
  leccode varchar(30),
  user_id varchar(20),
  orderno varchar(20),
  reg_dt date
);


-- =========== coop_coupon_mst ===========
CREATE TABLE coop_coupon_mst (
  coop_cd varchar(20),
  coupon_nm varchar(100),
  leccode varchar(20),
  st_dt varchar(10),
  ed_dt varchar(10),
  coupon_cnt BIGINT,
  coupon_use BIGINT,
  reg_dt date
);


-- =========== cop_seq ===========
CREATE TABLE cop_seq (
  table_name varchar(20) NOT NULL DEFAULT '',
  next_id decimal(30,0),
  PRIMARY KEY (table_name)
);

CREATE UNIQUE INDEX ux_cop_seq_pk ON cop_seq (table_name);
COMMENT ON COLUMN cop_seq.table_name IS '테이블명';
COMMENT ON COLUMN cop_seq.next_id IS '다음아이디';

