-- ============================================
-- V24__misc_other.sql
-- 분류외 잔여
-- 대상 테이블: 2개 (notuse_coupon_lecture, material_menu_mst)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== notuse_coupon_lecture ===========
CREATE TABLE notuse_coupon_lecture (
  leccode varchar(30)
);


-- =========== material_menu_mst ===========
CREATE TABLE material_menu_mst (
  menu_no INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  menu_id varchar(100),
  menu_title varchar(100) NOT NULL,
  menu_en varchar(100),
  menu_type varchar(20),
  menu_icon varchar(30),
  menu_url varchar(100),
  menu_classes varchar(20),
  menu_exact varchar(1),
  menu_target varchar(1),
  menu_breadcrumbs varchar(1),
  menu_external varchar(1),
  menu_left varchar(1),
  menu_path varchar(100),
  menu_element varchar(200),
  menu_layout varchar(20),
  menu_upper_id INTEGER,
  menu_depth INTEGER,
  menu_sort INTEGER,
  is_use varchar(1),
  PRIMARY KEY (menu_no)
);

COMMENT ON COLUMN material_menu_mst.menu_no IS '메뉴일련번호';
COMMENT ON COLUMN material_menu_mst.menu_id IS '메뉴 아이디';
COMMENT ON COLUMN material_menu_mst.menu_title IS '메뉴명';
COMMENT ON COLUMN material_menu_mst.menu_en IS '메뉴 영문명';
COMMENT ON COLUMN material_menu_mst.menu_type IS '메뉴 타입';
COMMENT ON COLUMN material_menu_mst.menu_icon IS '메뉴 아이콘';
COMMENT ON COLUMN material_menu_mst.menu_url IS '메뉴 URL';
COMMENT ON COLUMN material_menu_mst.menu_classes IS 'classes';
COMMENT ON COLUMN material_menu_mst.menu_exact IS '메뉴연결여부';
COMMENT ON COLUMN material_menu_mst.menu_target IS '메뉴 새창 여부';
COMMENT ON COLUMN material_menu_mst.menu_breadcrumbs IS 'breadcrumbs';
COMMENT ON COLUMN material_menu_mst.menu_external IS 'external';
COMMENT ON COLUMN material_menu_mst.menu_left IS '메뉴 여부';
COMMENT ON COLUMN material_menu_mst.menu_path IS '메뉴연결명';
COMMENT ON COLUMN material_menu_mst.menu_element IS '메뉴 링크';
COMMENT ON COLUMN material_menu_mst.menu_layout IS '화면 레이아웃';
COMMENT ON COLUMN material_menu_mst.menu_upper_id IS '메뉴 상위코드';
COMMENT ON COLUMN material_menu_mst.menu_depth IS '메뉴 단계';
COMMENT ON COLUMN material_menu_mst.menu_sort IS '메뉴순서';
COMMENT ON COLUMN material_menu_mst.is_use IS '사용여부';

