-- ============================================
-- V25__identity_admin.sql
-- 관리자 계정 (academy V2)
-- 대상 테이블: 1개 (id_admin)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== id_admin ===========
CREATE TABLE id_admin (
  admin_id char(36) NOT NULL,
  username varchar(64) NOT NULL,
  email varchar(255),
  password_hash varchar(100) NOT NULL,
  display_name varchar(100),
  role varchar(32) NOT NULL DEFAULT 'ROLE_ADMIN',
  enabled SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  last_login_at TIMESTAMP,
  PRIMARY KEY (admin_id)
);

CREATE UNIQUE INDEX ux_id_admin_username ON id_admin (username);
CREATE UNIQUE INDEX ux_id_admin_email ON id_admin (email);


-- ============================================
-- ON UPDATE CURRENT_TIMESTAMP 트리거
-- ============================================
-- 공용 트리거 함수 (한 번만 정의 — 첫 번째 V 에서만 CREATE)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_upd_dt_now') THEN
        EXECUTE $func$
            CREATE FUNCTION set_upd_dt_now() RETURNS trigger AS $body$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    -- 컬럼명이 upd_dt 또는 updated_at 인 경우 모두 처리
                    BEGIN
                        NEW.upd_dt := CURRENT_TIMESTAMP;
                    EXCEPTION WHEN OTHERS THEN
                        BEGIN
                            NEW.updated_at := CURRENT_TIMESTAMP;
                        EXCEPTION WHEN OTHERS THEN
                            NULL;
                        END;
                    END;
                END IF;
                RETURN NEW;
            END;
            $body$ LANGUAGE plpgsql;
        $func$;
    END IF;
END $$;


DROP TRIGGER IF EXISTS trg_id_admin_upd_dt ON id_admin;
CREATE TRIGGER trg_id_admin_upd_dt BEFORE UPDATE ON id_admin
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();
