-- ============================================
-- V26__enrollment_cart_order.sql
-- 수강 신청/장바구니/주문 (academy V5)
-- 대상 테이블: 5개 (en_cart_item, en_enrollment, od_order, od_order_item, od_payment)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== en_cart_item ===========
CREATE TABLE en_cart_item (
  cart_item_id char(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  mst_code varchar(32) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  price_snapshot decimal(12,0) NOT NULL DEFAULT 0,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (cart_item_id)
);

CREATE UNIQUE INDEX ux_en_cart_item_en_cart_user_mst ON en_cart_item (user_id, mst_code);
CREATE INDEX ix_en_cart_item_en_cart_user ON en_cart_item (user_id);

-- =========== en_enrollment ===========
CREATE TABLE en_enrollment (
  enrollment_id char(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  mst_code varchar(32) NOT NULL,
  order_id char(36),
  status varchar(32) NOT NULL DEFAULT 'ACTIVE',
  period_start date,
  period_end date,
  manual_progress INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  canceled_at TIMESTAMP,
  PRIMARY KEY (enrollment_id)
);

CREATE UNIQUE INDEX ux_en_enrollment_en_enroll_user_mst ON en_enrollment (user_id, mst_code);
CREATE INDEX ix_en_enrollment_en_enroll_user ON en_enrollment (user_id);
CREATE INDEX ix_en_enrollment_en_enroll_order ON en_enrollment (order_id);

-- =========== od_order ===========
CREATE TABLE od_order (
  order_id char(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  total_amount decimal(12,0) NOT NULL DEFAULT 0,
  discount_amount decimal(12,0) NOT NULL DEFAULT 0,
  mileage_used decimal(12,0) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP,
  canceled_at TIMESTAMP,
  PRIMARY KEY (order_id)
);

CREATE INDEX ix_od_order_user ON od_order (user_id);
CREATE INDEX ix_od_order_status ON od_order (status);

-- =========== od_order_item ===========
CREATE TABLE od_order_item (
  order_item_id char(36) NOT NULL,
  order_id char(36) NOT NULL,
  mst_code varchar(32) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price decimal(12,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_item_id)
);

CREATE INDEX ix_od_order_item_order ON od_order_item (order_id);

-- =========== od_payment ===========
CREATE TABLE od_payment (
  payment_id char(36) NOT NULL,
  order_id char(36) NOT NULL,
  method varchar(32) NOT NULL DEFAULT 'MOCK',
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  pg_txn_id varchar(128),
  amount decimal(12,0) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP,
  canceled_at TIMESTAMP,
  raw_response text,
  PRIMARY KEY (payment_id)
);

CREATE INDEX ix_od_payment_order ON od_payment (order_id);

