-- ============================================
-- V27__point_book.sql
-- 포인트/쿠폰/교재 (academy V6)
-- 대상 테이블: 6개 (pt_coupon, pt_coupon_user, pt_mileage_ledger, bk_book, bk_delivery_address...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== pt_coupon ===========
CREATE TABLE pt_coupon (
  coupon_id char(36) NOT NULL,
  name varchar(128) NOT NULL,
  discount_type varchar(16) NOT NULL DEFAULT 'AMOUNT',
  discount_value decimal(12,0) NOT NULL,
  min_order decimal(12,0) NOT NULL DEFAULT 0,
  valid_from TIMESTAMP NOT NULL,
  valid_to TIMESTAMP NOT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (coupon_id)
);


-- =========== pt_coupon_user ===========
CREATE TABLE pt_coupon_user (
  coupon_user_id char(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  coupon_id char(36) NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used_at TIMESTAMP,
  order_id char(36),
  PRIMARY KEY (coupon_user_id)
);

CREATE INDEX ix_pt_coupon_user_user ON pt_coupon_user (user_id);
CREATE INDEX ix_pt_coupon_user_coupon ON pt_coupon_user (coupon_id);

-- =========== pt_mileage_ledger ===========
CREATE TABLE pt_mileage_ledger (
  ledger_id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  user_id varchar(64) NOT NULL,
  delta decimal(12,0) NOT NULL,
  reason varchar(64) NOT NULL,
  order_id char(36),
  balance_after decimal(12,0) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ledger_id)
);

CREATE INDEX ix_pt_mileage_ledger_pt_mileage_user ON pt_mileage_ledger (user_id, created_at);

-- =========== bk_book ===========
CREATE TABLE bk_book (
  book_id char(36) NOT NULL,
  title varchar(255) NOT NULL,
  author varchar(128),
  price decimal(12,0) NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  PRIMARY KEY (book_id)
);


-- =========== bk_delivery_address ===========
CREATE TABLE bk_delivery_address (
  address_id char(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  recipient varchar(64) NOT NULL,
  phone varchar(32),
  zip_code varchar(16),
  address1 varchar(255) NOT NULL,
  address2 varchar(255),
  is_default SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (address_id)
);

CREATE INDEX ix_bk_delivery_address_bk_addr_user ON bk_delivery_address (user_id);

-- =========== bk_delivery ===========
CREATE TABLE bk_delivery (
  delivery_id char(36) NOT NULL,
  order_id char(36) NOT NULL,
  address_id char(36) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'READY',
  tracking_no varchar(64),
  carrier varchar(32),
  shipped_at TIMESTAMP,
  delivered_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (delivery_id)
);

CREATE INDEX ix_bk_delivery_order ON bk_delivery (order_id);


-- ============================================
-- ON UPDATE CURRENT_TIMESTAMP 트리거
-- ============================================
-- 공용 트리거 함수 (한 번만 정의 — 첫 번째 V 에서만 CREATE)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_upd_dt_now') THEN
        EXECUTE $func$
            CREATE FUNCTION set_upd_dt_now() RETURNS trigger AS $body$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    -- 컬럼명이 upd_dt 또는 updated_at 인 경우 모두 처리
                    BEGIN
                        NEW.upd_dt := CURRENT_TIMESTAMP;
                    EXCEPTION WHEN OTHERS THEN
                        BEGIN
                            NEW.updated_at := CURRENT_TIMESTAMP;
                        EXCEPTION WHEN OTHERS THEN
                            NULL;
                        END;
                    END;
                END IF;
                RETURN NEW;
            END;
            $body$ LANGUAGE plpgsql;
        $func$;
    END IF;
END $$;


DROP TRIGGER IF EXISTS trg_bk_book_upd_dt ON bk_book;
CREATE TRIGGER trg_bk_book_upd_dt BEFORE UPDATE ON bk_book
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();
