-- ============================================
-- V28__inquiry_extension.sql
-- 1:1 문의 확장 (academy V11~V12)
-- 대상 테이블: 1개 (tb_category_mapping)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_category_mapping ===========
CREATE TABLE tb_category_mapping (
  legacy_cs_div varchar(20) NOT NULL,
  legacy_cs_kind varchar(20) NOT NULL DEFAULT '',
  std_category varchar(30) NOT NULL,
  remark varchar(200),
  reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upd_dt TIMESTAMP /*PG_TODO_ON_UPDATE*/,
  PRIMARY KEY (legacy_cs_div, legacy_cs_kind)
);

CREATE INDEX ix_tb_category_mapping_std ON tb_category_mapping (std_category);
COMMENT ON COLUMN tb_category_mapping.legacy_cs_div IS 'TB_BOARD_CS.CS_DIV';
COMMENT ON COLUMN tb_category_mapping.legacy_cs_kind IS 'TB_BOARD_CS.CS_KIND. 빈 문자열 = CS_DIV 만으로 매칭';
COMMENT ON COLUMN tb_category_mapping.std_category IS '표준 4분류 — ACADEMIC|ORDER|SYSTEM|OTHER';


-- ============================================
-- ON UPDATE CURRENT_TIMESTAMP 트리거
-- ============================================
-- 공용 트리거 함수 (한 번만 정의 — 첫 번째 V 에서만 CREATE)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_upd_dt_now') THEN
        EXECUTE $func$
            CREATE FUNCTION set_upd_dt_now() RETURNS trigger AS $body$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    -- 컬럼명이 upd_dt 또는 updated_at 인 경우 모두 처리
                    BEGIN
                        NEW.upd_dt := CURRENT_TIMESTAMP;
                    EXCEPTION WHEN OTHERS THEN
                        BEGIN
                            NEW.updated_at := CURRENT_TIMESTAMP;
                        EXCEPTION WHEN OTHERS THEN
                            NULL;
                        END;
                    END;
                END IF;
                RETURN NEW;
            END;
            $body$ LANGUAGE plpgsql;
        $func$;
    END IF;
END $$;


DROP TRIGGER IF EXISTS trg_tb_category_mapping_upd_dt ON tb_category_mapping;
CREATE TRIGGER trg_tb_category_mapping_upd_dt BEFORE UPDATE ON tb_category_mapping
  FOR EACH ROW EXECUTE FUNCTION set_upd_dt_now();
