-- ============================================
-- V2__platform_common_codes.sql
-- 공통코드 마스터 (cmmn_*)
-- 대상 테이블: 3개 (cmmn_code, cmmn_cl_code, cmmn_detail_code)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== cmmn_code ===========
CREATE TABLE cmmn_code (
  code_id varchar(6) NOT NULL,
  code_id_nm varchar(60),
  code_id_dc varchar(200),
  use_at char(1),
  cl_code char(3),
  frst_regist_pnttm TIMESTAMP,
  frst_register_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  PRIMARY KEY (code_id)
);

CREATE UNIQUE INDEX ux_cmmn_code_pk ON cmmn_code (code_id);
CREATE INDEX ix_cmmn_code_i01 ON cmmn_code (cl_code);
COMMENT ON COLUMN cmmn_code.code_id IS '코드ID';
COMMENT ON COLUMN cmmn_code.code_id_nm IS '코드ID명';
COMMENT ON COLUMN cmmn_code.code_id_dc IS '코드ID설명';
COMMENT ON COLUMN cmmn_code.use_at IS '사용여부';
COMMENT ON COLUMN cmmn_code.cl_code IS '분류코드';
COMMENT ON COLUMN cmmn_code.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN cmmn_code.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN cmmn_code.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN cmmn_code.last_updusr_id IS '최종수정자ID';

-- =========== cmmn_cl_code ===========
CREATE TABLE cmmn_cl_code (
  cl_code char(3) NOT NULL,
  cl_code_nm varchar(60),
  cl_code_dc varchar(200),
  use_at char(1),
  frst_regist_pnttm TIMESTAMP,
  frst_register_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  PRIMARY KEY (cl_code)
);

CREATE UNIQUE INDEX ux_cmmn_cl_code_pk ON cmmn_cl_code (cl_code);
COMMENT ON COLUMN cmmn_cl_code.cl_code IS '분류코드';
COMMENT ON COLUMN cmmn_cl_code.cl_code_nm IS '분류코드명';
COMMENT ON COLUMN cmmn_cl_code.cl_code_dc IS '분류코드설명';
COMMENT ON COLUMN cmmn_cl_code.use_at IS '사용여부';
COMMENT ON COLUMN cmmn_cl_code.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN cmmn_cl_code.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN cmmn_cl_code.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN cmmn_cl_code.last_updusr_id IS '최종수정자ID';

-- =========== cmmn_detail_code ===========
CREATE TABLE cmmn_detail_code (
  code_id varchar(6) NOT NULL,
  code varchar(15) NOT NULL,
  code_nm varchar(60),
  code_dc varchar(200),
  use_at char(1),
  frst_regist_pnttm TIMESTAMP,
  frst_register_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  PRIMARY KEY (code_id, code)
);

CREATE UNIQUE INDEX ux_cmmn_detail_code_ccmmn_detail_code_pk ON cmmn_detail_code (code_id, code);
CREATE INDEX ix_cmmn_detail_code_ccmmn_detail_code_i01 ON cmmn_detail_code (code_id);
COMMENT ON COLUMN cmmn_detail_code.code_id IS '코드ID';
COMMENT ON COLUMN cmmn_detail_code.code IS '코드';
COMMENT ON COLUMN cmmn_detail_code.code_nm IS '코드명';
COMMENT ON COLUMN cmmn_detail_code.code_dc IS '코드설명';
COMMENT ON COLUMN cmmn_detail_code.use_at IS '사용여부';
COMMENT ON COLUMN cmmn_detail_code.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN cmmn_detail_code.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN cmmn_detail_code.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN cmmn_detail_code.last_updusr_id IS '최종수정자ID';

