-- ============================================
-- V3__platform_egov_user_master.sql
-- eGovFramework 회원 마스터 (3종)
-- 대상 테이블: 3개 (gnrl_mber, emplyr_info, entrprs_mber)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== gnrl_mber ===========
CREATE TABLE gnrl_mber (
  mber_id varchar(20) NOT NULL DEFAULT '',
  password varchar(200) NOT NULL,
  password_hint varchar(100),
  password_cnsr varchar(100),
  ihidnum varchar(200),
  mber_nm varchar(50),
  zip varchar(6),
  adres varchar(100),
  area_no varchar(4),
  mber_sttus varchar(15),
  detail_adres varchar(100),
  end_telno varchar(4),
  mbtlnum varchar(20),
  group_id char(20),
  mber_fxnum varchar(20),
  mber_email_adres varchar(50),
  middle_telno varchar(4),
  sbscrb_de TIMESTAMP,
  sexdstn_code char(1),
  esntl_id char(20),
  lock_at char(1),
  lock_cnt decimal(3,0),
  lock_last_pnttm TIMESTAMP,
  PRIMARY KEY (mber_id)
);

CREATE UNIQUE INDEX ux_gnrl_mber_pk ON gnrl_mber (mber_id);
CREATE INDEX ix_gnrl_mber_i01 ON gnrl_mber (group_id);
COMMENT ON COLUMN gnrl_mber.mber_id IS '회원ID';
COMMENT ON COLUMN gnrl_mber.password IS '비밀번호';
COMMENT ON COLUMN gnrl_mber.password_hint IS '비밀번호힌트';
COMMENT ON COLUMN gnrl_mber.password_cnsr IS '비밀번호정답';
COMMENT ON COLUMN gnrl_mber.ihidnum IS '주민등록번호';
COMMENT ON COLUMN gnrl_mber.mber_nm IS '회원명';
COMMENT ON COLUMN gnrl_mber.zip IS '우편번호';
COMMENT ON COLUMN gnrl_mber.adres IS '주소';
COMMENT ON COLUMN gnrl_mber.area_no IS '지역번호';
COMMENT ON COLUMN gnrl_mber.mber_sttus IS '회원상태';
COMMENT ON COLUMN gnrl_mber.detail_adres IS '상세주소';
COMMENT ON COLUMN gnrl_mber.end_telno IS '끝전화번호';
COMMENT ON COLUMN gnrl_mber.mbtlnum IS '이동전화번호';
COMMENT ON COLUMN gnrl_mber.group_id IS '그룹ID';
COMMENT ON COLUMN gnrl_mber.mber_fxnum IS '회원팩스번호';
COMMENT ON COLUMN gnrl_mber.mber_email_adres IS '회원이메일주소';
COMMENT ON COLUMN gnrl_mber.middle_telno IS '중간전화번호';
COMMENT ON COLUMN gnrl_mber.sbscrb_de IS '가입일자';
COMMENT ON COLUMN gnrl_mber.sexdstn_code IS '성별코드';
COMMENT ON COLUMN gnrl_mber.esntl_id IS '고유ID';
COMMENT ON COLUMN gnrl_mber.lock_at IS '잠금여부';
COMMENT ON COLUMN gnrl_mber.lock_cnt IS '잠금회수';
COMMENT ON COLUMN gnrl_mber.lock_last_pnttm IS '잠금최종시점';

-- =========== emplyr_info ===========
CREATE TABLE emplyr_info (
  emplyr_id varchar(20) NOT NULL,
  orgnzt_id char(20),
  user_nm varchar(60) NOT NULL,
  password varchar(200) NOT NULL,
  empl_no varchar(20),
  ihidnum varchar(200),
  sexdstn_code char(1),
  brthdy char(20),
  fxnum varchar(20),
  house_adres varchar(100),
  password_hint varchar(100),
  password_cnsr varchar(100),
  house_end_telno varchar(4),
  area_no varchar(4),
  detail_adres varchar(100),
  zip varchar(6),
  offm_telno varchar(20),
  mbtlnum varchar(20),
  email_adres varchar(50),
  ofcps_nm varchar(60),
  house_middle_telno varchar(4),
  group_id char(20),
  pstinst_code char(8),
  emplyr_sttus_code char(1),
  esntl_id char(20),
  crtfc_dn_value varchar(100),
  sbscrb_de TIMESTAMP,
  lock_at char(1),
  lock_cnt decimal(3,0),
  lock_last_pnttm TIMESTAMP,
  chg_pwd_last_pnttm TIMESTAMP,
  PRIMARY KEY (emplyr_id)
);

CREATE UNIQUE INDEX ux_emplyr_info_pk ON emplyr_info (emplyr_id);
CREATE INDEX ix_emplyr_info_i01 ON emplyr_info (orgnzt_id);
CREATE INDEX ix_emplyr_info_i02 ON emplyr_info (group_id);
COMMENT ON COLUMN emplyr_info.emplyr_id IS '업무사용자ID';
COMMENT ON COLUMN emplyr_info.orgnzt_id IS '조직ID';
COMMENT ON COLUMN emplyr_info.user_nm IS '사용자명';
COMMENT ON COLUMN emplyr_info.password IS '비밀번호';
COMMENT ON COLUMN emplyr_info.empl_no IS '사원번호';
COMMENT ON COLUMN emplyr_info.ihidnum IS '주민등록번호';
COMMENT ON COLUMN emplyr_info.sexdstn_code IS '성별코드';
COMMENT ON COLUMN emplyr_info.brthdy IS '생일';
COMMENT ON COLUMN emplyr_info.fxnum IS '팩스번호';
COMMENT ON COLUMN emplyr_info.house_adres IS '주택주소';
COMMENT ON COLUMN emplyr_info.password_hint IS '비밀번호힌트';
COMMENT ON COLUMN emplyr_info.password_cnsr IS '비밀번호정답';
COMMENT ON COLUMN emplyr_info.house_end_telno IS '주택끝전화번호';
COMMENT ON COLUMN emplyr_info.area_no IS '지역번호';
COMMENT ON COLUMN emplyr_info.detail_adres IS '상세주소';
COMMENT ON COLUMN emplyr_info.zip IS '우편번호';
COMMENT ON COLUMN emplyr_info.offm_telno IS '사무실전화번호';
COMMENT ON COLUMN emplyr_info.mbtlnum IS '이동전화번호';
COMMENT ON COLUMN emplyr_info.email_adres IS '이메일주소';
COMMENT ON COLUMN emplyr_info.ofcps_nm IS '직위명';
COMMENT ON COLUMN emplyr_info.house_middle_telno IS '주택중간전화번호';
COMMENT ON COLUMN emplyr_info.group_id IS '그룹ID';
COMMENT ON COLUMN emplyr_info.pstinst_code IS '소속기관코드';
COMMENT ON COLUMN emplyr_info.emplyr_sttus_code IS '사용자상태코드';
COMMENT ON COLUMN emplyr_info.esntl_id IS '고유ID';
COMMENT ON COLUMN emplyr_info.crtfc_dn_value IS '인증DN값';
COMMENT ON COLUMN emplyr_info.sbscrb_de IS '가입일자';
COMMENT ON COLUMN emplyr_info.lock_at IS '잠금여부';
COMMENT ON COLUMN emplyr_info.lock_cnt IS '잠금회수';
COMMENT ON COLUMN emplyr_info.lock_last_pnttm IS '잠금최종시점';
COMMENT ON COLUMN emplyr_info.chg_pwd_last_pnttm IS '비밀번호변겨이점';

-- =========== entrprs_mber ===========
CREATE TABLE entrprs_mber (
  entrprs_mber_id varchar(20) NOT NULL DEFAULT '',
  entrprs_se_code char(8),
  bizrno varchar(10),
  jurirno varchar(13),
  cmpny_nm varchar(60) NOT NULL,
  cxfc varchar(50),
  zip varchar(6) NOT NULL,
  adres varchar(100) NOT NULL,
  entrprs_middle_telno varchar(4) NOT NULL,
  fxnum varchar(20),
  induty_code char(1),
  applcnt_nm varchar(50) NOT NULL,
  applcnt_ihidnum varchar(200),
  sbscrb_de TIMESTAMP,
  entrprs_mber_sttus varchar(15),
  entrprs_mber_password varchar(200),
  entrprs_mber_password_hint varchar(100) NOT NULL,
  entrprs_mber_password_cnsr varchar(100) NOT NULL,
  group_id char(20),
  detail_adres varchar(100),
  entrprs_end_telno varchar(4) NOT NULL,
  area_no varchar(4) NOT NULL,
  applcnt_email_adres varchar(50) NOT NULL,
  esntl_id char(20) NOT NULL,
  lock_at char(1),
  lock_cnt decimal(3,0),
  lock_last_pnttm TIMESTAMP,
  PRIMARY KEY (entrprs_mber_id)
);

CREATE UNIQUE INDEX ux_entrprs_mber_pk ON entrprs_mber (entrprs_mber_id);
CREATE INDEX ix_entrprs_mber_i01 ON entrprs_mber (group_id);
COMMENT ON COLUMN entrprs_mber.entrprs_mber_id IS '기업회원ID';
COMMENT ON COLUMN entrprs_mber.entrprs_se_code IS '기업구분코드';
COMMENT ON COLUMN entrprs_mber.bizrno IS '사업자등록번호';
COMMENT ON COLUMN entrprs_mber.jurirno IS '법인등록번호';
COMMENT ON COLUMN entrprs_mber.cmpny_nm IS '회사명';
COMMENT ON COLUMN entrprs_mber.cxfc IS '대표이사';
COMMENT ON COLUMN entrprs_mber.zip IS '우편번호';
COMMENT ON COLUMN entrprs_mber.adres IS '주소';
COMMENT ON COLUMN entrprs_mber.entrprs_middle_telno IS '기업중간전화번호';
COMMENT ON COLUMN entrprs_mber.fxnum IS '팩스번호';
COMMENT ON COLUMN entrprs_mber.induty_code IS '업종코드';
COMMENT ON COLUMN entrprs_mber.applcnt_nm IS '신청인명';
COMMENT ON COLUMN entrprs_mber.applcnt_ihidnum IS '신청인주민등록번호';
COMMENT ON COLUMN entrprs_mber.sbscrb_de IS '가입일자';
COMMENT ON COLUMN entrprs_mber.entrprs_mber_sttus IS '기업회원상태';
COMMENT ON COLUMN entrprs_mber.entrprs_mber_password IS '기업회원비밀번호';
COMMENT ON COLUMN entrprs_mber.entrprs_mber_password_hint IS '기업회원비밀번호힌트';
COMMENT ON COLUMN entrprs_mber.entrprs_mber_password_cnsr IS '기업회원비밀번호정답';
COMMENT ON COLUMN entrprs_mber.group_id IS '그룹ID';
COMMENT ON COLUMN entrprs_mber.detail_adres IS '상세주소';
COMMENT ON COLUMN entrprs_mber.entrprs_end_telno IS '기업끝전화번호';
COMMENT ON COLUMN entrprs_mber.area_no IS '지역번호';
COMMENT ON COLUMN entrprs_mber.applcnt_email_adres IS '신청자이메일주소';
COMMENT ON COLUMN entrprs_mber.esntl_id IS '고유ID';
COMMENT ON COLUMN entrprs_mber.lock_at IS '잠금여부';
COMMENT ON COLUMN entrprs_mber.lock_cnt IS '잠금회수';
COMMENT ON COLUMN entrprs_mber.lock_last_pnttm IS '잠금최종시점';

