-- ============================================
-- V4__platform_egov_auth_log.sql
-- eGov 권한/로그/사용자 (10종)
-- 대상 테이블: 10개 (author_info, role_info, roles_hierarchy, author_role_relate, emplyrscrtyestbs...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== author_info ===========
CREATE TABLE author_info (
  author_code varchar(30) NOT NULL DEFAULT '',
  author_nm varchar(60) NOT NULL,
  author_dc varchar(200),
  author_creat_de char(20) NOT NULL,
  PRIMARY KEY (author_code)
);

CREATE UNIQUE INDEX ux_author_info_pk ON author_info (author_code);
COMMENT ON COLUMN author_info.author_code IS '권한코드';
COMMENT ON COLUMN author_info.author_nm IS '권한명';
COMMENT ON COLUMN author_info.author_dc IS '권한설명';
COMMENT ON COLUMN author_info.author_creat_de IS '권한생성일';

-- =========== role_info ===========
CREATE TABLE role_info (
  role_code varchar(50) NOT NULL DEFAULT '',
  role_nm varchar(60) NOT NULL,
  role_pttrn varchar(300),
  role_dc varchar(200),
  role_ty varchar(80),
  role_sort varchar(10),
  role_creat_de char(20) NOT NULL,
  PRIMARY KEY (role_code)
);

CREATE UNIQUE INDEX ux_role_info_pk ON role_info (role_code);
COMMENT ON COLUMN role_info.role_code IS '롤코드';
COMMENT ON COLUMN role_info.role_nm IS '롤명';
COMMENT ON COLUMN role_info.role_pttrn IS '롤패턴';
COMMENT ON COLUMN role_info.role_dc IS '롤설명';
COMMENT ON COLUMN role_info.role_ty IS '롤유형';
COMMENT ON COLUMN role_info.role_sort IS '롤정렬';
COMMENT ON COLUMN role_info.role_creat_de IS '롤생성일';

-- =========== roles_hierarchy ===========
CREATE TABLE roles_hierarchy (
  parnts_role varchar(30) NOT NULL,
  chldrn_role varchar(30) NOT NULL,
  PRIMARY KEY (parnts_role, chldrn_role),
  CONSTRAINT roles_hierarchy_fk1 FOREIGN KEY (parnts_role) REFERENCES author_info (author_code) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT roles_hierarchy_fk2 FOREIGN KEY (chldrn_role) REFERENCES author_info (author_code) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX ux_roles_hierarchy_pk ON roles_hierarchy (parnts_role, chldrn_role);
CREATE UNIQUE INDEX ux_roles_hierarchy_i01 ON roles_hierarchy (parnts_role);
CREATE INDEX ix_roles_hierarchy_i02 ON roles_hierarchy (chldrn_role);
COMMENT ON COLUMN roles_hierarchy.parnts_role IS '부모롤';
COMMENT ON COLUMN roles_hierarchy.chldrn_role IS '자식롤';

-- =========== author_role_relate ===========
CREATE TABLE author_role_relate (
  author_code varchar(30) NOT NULL,
  role_code varchar(50) NOT NULL,
  creat_dt TIMESTAMP,
  PRIMARY KEY (author_code, role_code),
  CONSTRAINT author_role_relate_fk1 FOREIGN KEY (author_code) REFERENCES author_info (author_code) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT author_role_relate_fk2 FOREIGN KEY (role_code) REFERENCES role_info (role_code) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX ux_author_role_relate_pk ON author_role_relate (author_code, role_code);
CREATE INDEX ix_author_role_relate_i01 ON author_role_relate (author_code);
CREATE INDEX ix_author_role_relate_i02 ON author_role_relate (role_code);
COMMENT ON COLUMN author_role_relate.author_code IS '권한코드';
COMMENT ON COLUMN author_role_relate.role_code IS '롤코드';
COMMENT ON COLUMN author_role_relate.creat_dt IS '생성일시';

-- =========== emplyrscrtyestbs ===========
CREATE TABLE emplyrscrtyestbs (
  scrty_dtrmn_trget_id varchar(20) NOT NULL,
  mber_ty_code char(5),
  author_code varchar(30) NOT NULL,
  PRIMARY KEY (scrty_dtrmn_trget_id)
);

CREATE UNIQUE INDEX ux_emplyrscrtyestbs_pk ON emplyrscrtyestbs (scrty_dtrmn_trget_id);
CREATE INDEX ix_emplyrscrtyestbs_i04 ON emplyrscrtyestbs (author_code);
COMMENT ON COLUMN emplyrscrtyestbs.scrty_dtrmn_trget_id IS '보안설정대상ID';
COMMENT ON COLUMN emplyrscrtyestbs.mber_ty_code IS '회원유형코드';
COMMENT ON COLUMN emplyrscrtyestbs.author_code IS '권한코드';

-- =========== sys_log ===========
CREATE TABLE sys_log (
  requst_id varchar(20) NOT NULL,
  job_se_code char(3),
  instt_code char(7),
  occrrnc_de TIMESTAMP,
  rqester_ip varchar(23),
  rqester_id varchar(20),
  trget_menu_nm varchar(255),
  svc_nm varchar(255),
  method_nm varchar(60),
  process_se_code char(3),
  process_co decimal(10,0),
  process_time varchar(14),
  rspns_code char(3),
  error_se char(1),
  error_co decimal(10,0),
  error_code char(3),
  PRIMARY KEY (requst_id)
);

CREATE UNIQUE INDEX ux_sys_log_pk ON sys_log (requst_id);
COMMENT ON COLUMN sys_log.requst_id IS '요청ID';
COMMENT ON COLUMN sys_log.job_se_code IS '업무구분코드';
COMMENT ON COLUMN sys_log.instt_code IS '기관코드';
COMMENT ON COLUMN sys_log.occrrnc_de IS '발생일';
COMMENT ON COLUMN sys_log.rqester_ip IS '요청자IP';
COMMENT ON COLUMN sys_log.rqester_id IS '요청자ID';
COMMENT ON COLUMN sys_log.trget_menu_nm IS '대상메뉴명';
COMMENT ON COLUMN sys_log.svc_nm IS '서비스명';
COMMENT ON COLUMN sys_log.method_nm IS '메서드명';
COMMENT ON COLUMN sys_log.process_se_code IS '처리구분코드';
COMMENT ON COLUMN sys_log.process_co IS '처리수';
COMMENT ON COLUMN sys_log.process_time IS '처리시간';
COMMENT ON COLUMN sys_log.rspns_code IS '응답코드';
COMMENT ON COLUMN sys_log.error_se IS '오류구분';
COMMENT ON COLUMN sys_log.error_co IS '오류수';
COMMENT ON COLUMN sys_log.error_code IS '오류코드';

-- =========== mb_access_log ===========
CREATE TABLE mb_access_log (
  access_dt date,
  userid varchar(20),
  user_ip varchar(100),
  is_login varchar(1),
  is_lec_open varchar(1)
);


-- =========== off_user ===========
CREATE TABLE off_user (
  users_group_code BIGINT,
  userid varchar(20),
  userpass varchar(20),
  username varchar(50),
  sexcode varchar(6),
  passhintqcode varchar(6),
  passhintanswer varchar(200),
  birthday varchar(8),
  email varchar(50),
  homeurl varchar(100),
  zipcd varchar(6),
  addr varchar(200),
  addr2 varchar(100),
  regdate date,
  point BIGINT,
  mailling_yn varchar(1),
  favorites varchar(200),
  path_history varchar(200),
  memo BYTEA,
  relation BIGINT,
  oldid_hl varchar(20),
  oldid_gosimain varchar(20),
  oldid_passhaja varchar(20),
  oldid_bookgosimain varchar(20),
  id_url varchar(200),
  user_ip varchar(15),
  userregtype varchar(1),
  pub_code varchar(50)
);


-- =========== on_user ===========
CREATE TABLE on_user (
  user_id varchar(30),
  user_nm varchar(50),
  user_nicknm varchar(50),
  user_position varchar(100),
  sex varchar(1),
  user_role varchar(4),
  admin_role varchar(1),
  user_pwd varchar(20),
  birth_day varchar(8),
  email varchar(50),
  zip_code varchar(7),
  address1 varchar(150),
  address2 varchar(150),
  category_code varchar(10),
  user_point varchar(1000),
  isuse varchar(1),
  reg_dt date,
  upd_dt date,
  remark varchar(1000),
  memo varchar(8)
);


-- =========== tbl_users ===========
CREATE TABLE tbl_users (
  user_id varchar(30),
  user_nm varchar(50),
  user_pwd varchar(4000),
  email varchar(100)
);


