-- ============================================
-- V5__platform_egov_bbs.sql
-- eGov 게시판 (4종)
-- 대상 테이블: 4개 (comtnbbs, comtnbbsmaster, comtnbbsmasteroptn, comtnbbsuse)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== comtnbbs ===========
CREATE TABLE comtnbbs (
  ntt_id decimal(20,0) NOT NULL,
  bbs_id char(20) NOT NULL,
  ntt_no decimal(20,0),
  ntt_sj varchar(2000),
  ntt_cn TEXT,
  answer_at char(1),
  parntsctt_no decimal(10,0),
  answer_lc decimal(8,0),
  sort_ordr decimal(8,0),
  rdcnt decimal(10,0),
  use_at char(1) NOT NULL,
  ntce_bgnde char(20),
  ntce_endde char(20),
  ntcr_id varchar(20),
  ntcr_nm varchar(20),
  password varchar(200),
  atch_file_id char(20),
  notice_at char(1),
  sj_bold_at char(1),
  secret_at char(1),
  frst_regist_pnttm TIMESTAMP NOT NULL,
  frst_register_id varchar(20) NOT NULL,
  last_updt_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  blog_id char(20),
  PRIMARY KEY (ntt_id, bbs_id)
);

CREATE UNIQUE INDEX ux_comtnbbs_pk ON comtnbbs (ntt_id, bbs_id);
CREATE INDEX ix_comtnbbs_i01 ON comtnbbs (bbs_id);
COMMENT ON COLUMN comtnbbs.ntt_id IS '게시물ID';
COMMENT ON COLUMN comtnbbs.bbs_id IS '게시판ID';
COMMENT ON COLUMN comtnbbs.ntt_no IS '게시물번호';
COMMENT ON COLUMN comtnbbs.ntt_sj IS '게시물제목';
COMMENT ON COLUMN comtnbbs.ntt_cn IS '게시물내용';
COMMENT ON COLUMN comtnbbs.answer_at IS '댓글여부';
COMMENT ON COLUMN comtnbbs.parntsctt_no IS '부모글번호';
COMMENT ON COLUMN comtnbbs.answer_lc IS '댓글위치';
COMMENT ON COLUMN comtnbbs.sort_ordr IS '정렬순서';
COMMENT ON COLUMN comtnbbs.rdcnt IS '조회수';
COMMENT ON COLUMN comtnbbs.use_at IS '사용여부';
COMMENT ON COLUMN comtnbbs.ntce_bgnde IS '게시시작일';
COMMENT ON COLUMN comtnbbs.ntce_endde IS '게시종료일';
COMMENT ON COLUMN comtnbbs.ntcr_id IS '게시자ID';
COMMENT ON COLUMN comtnbbs.ntcr_nm IS '게시자명';
COMMENT ON COLUMN comtnbbs.password IS '비밀번호';
COMMENT ON COLUMN comtnbbs.atch_file_id IS '첨부파일ID';
COMMENT ON COLUMN comtnbbs.notice_at IS '공지사항여부';
COMMENT ON COLUMN comtnbbs.sj_bold_at IS '제목볼드여부';
COMMENT ON COLUMN comtnbbs.secret_at IS '비밀글여부';
COMMENT ON COLUMN comtnbbs.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnbbs.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnbbs.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN comtnbbs.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtnbbs.blog_id IS '블로그 ID';

-- =========== comtnbbsmaster ===========
CREATE TABLE comtnbbsmaster (
  bbs_id char(20) NOT NULL,
  bbs_nm varchar(255) NOT NULL,
  bbs_intrcn varchar(2400),
  bbs_ty_code char(6) NOT NULL,
  reply_posbl_at char(1),
  file_atch_posbl_at char(1) NOT NULL,
  atch_posbl_file_number decimal(2,0) NOT NULL,
  atch_posbl_file_size decimal(8,0),
  use_at char(1) NOT NULL,
  tmplat_id char(20),
  cmmnty_id char(20),
  frst_register_id varchar(20) NOT NULL,
  frst_regist_pnttm TIMESTAMP NOT NULL,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  blog_id char(20),
  blog_at char(2),
  PRIMARY KEY (bbs_id)
);

CREATE UNIQUE INDEX ux_comtnbbsmaster_pk ON comtnbbsmaster (bbs_id);
COMMENT ON COLUMN comtnbbsmaster.bbs_id IS '게시판ID';
COMMENT ON COLUMN comtnbbsmaster.bbs_nm IS '게시판명';
COMMENT ON COLUMN comtnbbsmaster.bbs_intrcn IS '게시판소개';
COMMENT ON COLUMN comtnbbsmaster.bbs_ty_code IS '게시판유형코드';
COMMENT ON COLUMN comtnbbsmaster.reply_posbl_at IS '답장가능여부';
COMMENT ON COLUMN comtnbbsmaster.file_atch_posbl_at IS '파일첨부가능여부';
COMMENT ON COLUMN comtnbbsmaster.atch_posbl_file_number IS '첨부가능파일숫자';
COMMENT ON COLUMN comtnbbsmaster.atch_posbl_file_size IS '첨부가능파일사이즈';
COMMENT ON COLUMN comtnbbsmaster.use_at IS '사용여부';
COMMENT ON COLUMN comtnbbsmaster.tmplat_id IS '템플릿ID';
COMMENT ON COLUMN comtnbbsmaster.cmmnty_id IS '커뮤니티ID';
COMMENT ON COLUMN comtnbbsmaster.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnbbsmaster.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnbbsmaster.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtnbbsmaster.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN comtnbbsmaster.blog_id IS '블로그 ID';
COMMENT ON COLUMN comtnbbsmaster.blog_at IS '블로그 여부';

-- =========== comtnbbsmasteroptn ===========
CREATE TABLE comtnbbsmasteroptn (
  bbs_id char(20) NOT NULL,
  answer_at char(1) NOT NULL,
  stsfdg_at char(1) NOT NULL,
  frst_regist_pnttm TIMESTAMP NOT NULL,
  last_updt_pnttm TIMESTAMP,
  frst_register_id varchar(20) NOT NULL,
  last_updusr_id varchar(20),
  PRIMARY KEY (bbs_id)
);

CREATE UNIQUE INDEX ux_comtnbbsmasteroptn_pk ON comtnbbsmasteroptn (bbs_id);
COMMENT ON COLUMN comtnbbsmasteroptn.bbs_id IS '게시판ID';
COMMENT ON COLUMN comtnbbsmasteroptn.answer_at IS '댓글여부';
COMMENT ON COLUMN comtnbbsmasteroptn.stsfdg_at IS '만족도여부';
COMMENT ON COLUMN comtnbbsmasteroptn.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnbbsmasteroptn.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN comtnbbsmasteroptn.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnbbsmasteroptn.last_updusr_id IS '최종수정자ID';

-- =========== comtnbbsuse ===========
CREATE TABLE comtnbbsuse (
  bbs_id char(20) NOT NULL,
  trget_id char(20) NOT NULL DEFAULT '',
  use_at char(1) NOT NULL,
  regist_se_code char(6),
  frst_regist_pnttm TIMESTAMP,
  frst_register_id varchar(20) NOT NULL,
  last_updt_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  PRIMARY KEY (bbs_id, trget_id)
);

CREATE UNIQUE INDEX ux_comtnbbsuse_pk ON comtnbbsuse (bbs_id, trget_id);
CREATE INDEX ix_comtnbbsuse_i01 ON comtnbbsuse (bbs_id);
COMMENT ON COLUMN comtnbbsuse.bbs_id IS '게시판ID';
COMMENT ON COLUMN comtnbbsuse.trget_id IS '대상ID';
COMMENT ON COLUMN comtnbbsuse.use_at IS '사용여부';
COMMENT ON COLUMN comtnbbsuse.regist_se_code IS '등록구분코드';
COMMENT ON COLUMN comtnbbsuse.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnbbsuse.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnbbsuse.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN comtnbbsuse.last_updusr_id IS '최종수정자ID';

