-- ============================================
-- V6__platform_egov_log.sql
-- eGov 로그/모니터링 (15종)
-- 대상 테이블: 14개 (comtnloginlog, comtnloginpolicy, comtnntwrksvcmntrng, comtnntwrksvcmntrngloginfo, comtnprivacylog...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== comtnloginlog ===========
CREATE TABLE comtnloginlog (
  log_id char(20) NOT NULL,
  conect_id varchar(20),
  conect_ip varchar(23),
  conect_mthd char(4),
  error_occrrnc_at char(1),
  error_code char(3),
  creat_dt TIMESTAMP,
  PRIMARY KEY (log_id)
);

CREATE UNIQUE INDEX ux_comtnloginlog_pk ON comtnloginlog (log_id);
COMMENT ON COLUMN comtnloginlog.log_id IS '로그ID';
COMMENT ON COLUMN comtnloginlog.conect_id IS '접속ID';
COMMENT ON COLUMN comtnloginlog.conect_ip IS '접속IP';
COMMENT ON COLUMN comtnloginlog.conect_mthd IS '접속방식';
COMMENT ON COLUMN comtnloginlog.error_occrrnc_at IS '오류발생여부';
COMMENT ON COLUMN comtnloginlog.error_code IS '오류코드';
COMMENT ON COLUMN comtnloginlog.creat_dt IS '생성일시';

-- =========== comtnloginpolicy ===========
CREATE TABLE comtnloginpolicy (
  emplyr_id varchar(20) NOT NULL DEFAULT '',
  ip_info varchar(23) NOT NULL,
  dplct_perm_at char(1) NOT NULL,
  lmtt_at char(1) NOT NULL,
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  PRIMARY KEY (emplyr_id)
);

CREATE UNIQUE INDEX ux_comtnloginpolicy_pk ON comtnloginpolicy (emplyr_id);
COMMENT ON COLUMN comtnloginpolicy.emplyr_id IS '업무사용자ID';
COMMENT ON COLUMN comtnloginpolicy.ip_info IS 'IP정보';
COMMENT ON COLUMN comtnloginpolicy.dplct_perm_at IS '중복허용여부';
COMMENT ON COLUMN comtnloginpolicy.lmtt_at IS '제한여부';
COMMENT ON COLUMN comtnloginpolicy.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnloginpolicy.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnloginpolicy.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtnloginpolicy.last_updt_pnttm IS '최종수정시점';

-- =========== comtnntwrksvcmntrng ===========
CREATE TABLE comtnntwrksvcmntrng (
  sys_ip varchar(23) NOT NULL,
  sys_port decimal(5,0) NOT NULL,
  sys_nm varchar(255) NOT NULL,
  mngr_nm varchar(60),
  mngr_email_adres varchar(50),
  mntrng_sttus char(2),
  creat_dt TIMESTAMP,
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20) NOT NULL,
  last_updt_pnttm TIMESTAMP NOT NULL,
  PRIMARY KEY (sys_ip, sys_port)
);

CREATE UNIQUE INDEX ux_comtnntwrksvcmntrng_pk ON comtnntwrksvcmntrng (sys_ip, sys_port);
COMMENT ON COLUMN comtnntwrksvcmntrng.sys_ip IS '시스템IP';
COMMENT ON COLUMN comtnntwrksvcmntrng.sys_port IS '시스템포트';
COMMENT ON COLUMN comtnntwrksvcmntrng.sys_nm IS '시스템명';
COMMENT ON COLUMN comtnntwrksvcmntrng.mngr_nm IS '관리자명';
COMMENT ON COLUMN comtnntwrksvcmntrng.mngr_email_adres IS '관리자이메일주소';
COMMENT ON COLUMN comtnntwrksvcmntrng.mntrng_sttus IS '모니터링상태';
COMMENT ON COLUMN comtnntwrksvcmntrng.creat_dt IS '생성일시';
COMMENT ON COLUMN comtnntwrksvcmntrng.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnntwrksvcmntrng.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnntwrksvcmntrng.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtnntwrksvcmntrng.last_updt_pnttm IS '최종수정시점';

-- =========== comtnntwrksvcmntrngloginfo ===========
CREATE TABLE comtnntwrksvcmntrngloginfo (
  sys_ip varchar(23) NOT NULL,
  sys_port decimal(5,0) NOT NULL,
  sys_nm varchar(255) NOT NULL,
  mntrng_sttus char(2),
  log_info varchar(2000),
  creat_dt TIMESTAMP,
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20) NOT NULL,
  last_updt_pnttm TIMESTAMP NOT NULL,
  log_id char(20) NOT NULL DEFAULT '',
  PRIMARY KEY (sys_ip, sys_port, log_id)
);

CREATE UNIQUE INDEX ux_comtnntwrksvcmntrngloginfo_pk ON comtnntwrksvcmntrngloginfo (sys_ip, sys_port, log_id);
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.sys_ip IS '시스템IP';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.sys_port IS '시스템포트';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.sys_nm IS '시스템명';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.mntrng_sttus IS '모니터링상태';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.log_info IS '로그정보';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.creat_dt IS '생성일시';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.last_updt_pnttm IS '최종수정시점';
COMMENT ON COLUMN comtnntwrksvcmntrngloginfo.log_id IS '로그ID';

-- =========== comtnprivacylog ===========
CREATE TABLE comtnprivacylog (
  requst_id varchar(20) NOT NULL,
  inqire_dt TIMESTAMP NOT NULL,
  srvc_nm varchar(500),
  inqire_info varchar(100),
  rqester_id varchar(20),
  rqester_ip varchar(23),
  PRIMARY KEY (requst_id)
);

CREATE UNIQUE INDEX ux_comtnprivacylog_pk ON comtnprivacylog (requst_id);
COMMENT ON COLUMN comtnprivacylog.requst_id IS '요청 ID';
COMMENT ON COLUMN comtnprivacylog.inqire_dt IS '조회일시';
COMMENT ON COLUMN comtnprivacylog.srvc_nm IS '서비스 명';
COMMENT ON COLUMN comtnprivacylog.inqire_info IS '조회 정보 명';
COMMENT ON COLUMN comtnprivacylog.rqester_id IS '요청자아이디';
COMMENT ON COLUMN comtnprivacylog.rqester_ip IS '요청아이피';

-- =========== comtntrsmrcvlog ===========
CREATE TABLE comtntrsmrcvlog (
  requst_id varchar(20) NOT NULL,
  occrrnc_de char(20),
  trsmrcv_se_code char(3),
  cntc_id char(8),
  provd_instt_id char(8),
  provd_sys_id char(8),
  provd_svc_id char(8),
  requst_instt_id char(8),
  requst_sys_id char(8),
  requst_trnsmit_tm varchar(14),
  requst_recptn_tm varchar(14),
  rspns_trnsmit_tm varchar(14),
  rspns_recptn_tm varchar(14),
  result_code varchar(4),
  result_mssage varchar(4000),
  frst_regist_pnttm TIMESTAMP,
  rqester_id varchar(20),
  PRIMARY KEY (requst_id)
);

CREATE UNIQUE INDEX ux_comtntrsmrcvlog_pk ON comtntrsmrcvlog (requst_id);
COMMENT ON COLUMN comtntrsmrcvlog.requst_id IS '요청ID';
COMMENT ON COLUMN comtntrsmrcvlog.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtntrsmrcvlog.trsmrcv_se_code IS '송수신구분코드';
COMMENT ON COLUMN comtntrsmrcvlog.cntc_id IS '연계ID';
COMMENT ON COLUMN comtntrsmrcvlog.provd_instt_id IS '제공기관ID';
COMMENT ON COLUMN comtntrsmrcvlog.provd_sys_id IS '제공시스템ID';
COMMENT ON COLUMN comtntrsmrcvlog.provd_svc_id IS '제공서비스ID';
COMMENT ON COLUMN comtntrsmrcvlog.requst_instt_id IS '요청기관ID';
COMMENT ON COLUMN comtntrsmrcvlog.requst_sys_id IS '요청시스템ID';
COMMENT ON COLUMN comtntrsmrcvlog.requst_trnsmit_tm IS '요청송신시각';
COMMENT ON COLUMN comtntrsmrcvlog.requst_recptn_tm IS '요청수신시각';
COMMENT ON COLUMN comtntrsmrcvlog.rspns_trnsmit_tm IS '응답송신시각';
COMMENT ON COLUMN comtntrsmrcvlog.rspns_recptn_tm IS '응답수신시각';
COMMENT ON COLUMN comtntrsmrcvlog.result_code IS '결과코드';
COMMENT ON COLUMN comtntrsmrcvlog.result_mssage IS '결과메시지';
COMMENT ON COLUMN comtntrsmrcvlog.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtntrsmrcvlog.rqester_id IS '요청자ID';

-- =========== comtnuserlog ===========
CREATE TABLE comtnuserlog (
  occrrnc_de char(8) NOT NULL DEFAULT '',
  rqester_id varchar(20) NOT NULL DEFAULT '',
  svc_nm varchar(255) NOT NULL DEFAULT '',
  method_nm varchar(60) NOT NULL DEFAULT '',
  creat_co decimal(10,0),
  updt_co decimal(10,0),
  rdcnt decimal(10,0),
  delete_co decimal(10,0),
  outpt_co decimal(10,0),
  error_co decimal(10,0),
  PRIMARY KEY (occrrnc_de, rqester_id, svc_nm, method_nm)
);

CREATE UNIQUE INDEX ux_comtnuserlog_pk ON comtnuserlog (occrrnc_de, rqester_id, svc_nm, method_nm);
COMMENT ON COLUMN comtnuserlog.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtnuserlog.rqester_id IS '요청자ID';
COMMENT ON COLUMN comtnuserlog.svc_nm IS '서비스명';
COMMENT ON COLUMN comtnuserlog.method_nm IS '메서드명';
COMMENT ON COLUMN comtnuserlog.creat_co IS '생성수';
COMMENT ON COLUMN comtnuserlog.updt_co IS '수정수';
COMMENT ON COLUMN comtnuserlog.rdcnt IS '조회수';
COMMENT ON COLUMN comtnuserlog.delete_co IS '삭제수';
COMMENT ON COLUMN comtnuserlog.outpt_co IS '출력수';
COMMENT ON COLUMN comtnuserlog.error_co IS '오류수';

-- =========== comtsbbssummary ===========
CREATE TABLE comtsbbssummary (
  occrrnc_de char(20) NOT NULL DEFAULT '',
  stats_se varchar(10) NOT NULL DEFAULT '',
  detail_stats_se varchar(10) NOT NULL DEFAULT '',
  creat_co decimal(10,0),
  tot_rdcnt decimal(10,0),
  avrg_rdcnt decimal(10,0),
  top_inqire_bbsctt_id varchar(20),
  mumm_inqire_bbsctt_id varchar(20),
  top_ntcr_id varchar(20),
  PRIMARY KEY (occrrnc_de, stats_se, detail_stats_se)
);

CREATE UNIQUE INDEX ux_comtsbbssummary_pk ON comtsbbssummary (occrrnc_de, stats_se, detail_stats_se);
COMMENT ON COLUMN comtsbbssummary.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtsbbssummary.stats_se IS '통계구분';
COMMENT ON COLUMN comtsbbssummary.detail_stats_se IS '세부통계구분';
COMMENT ON COLUMN comtsbbssummary.creat_co IS '생성수';
COMMENT ON COLUMN comtsbbssummary.tot_rdcnt IS '총조회수';
COMMENT ON COLUMN comtsbbssummary.avrg_rdcnt IS '평균조회수';
COMMENT ON COLUMN comtsbbssummary.top_inqire_bbsctt_id IS '최고조회게시글ID';
COMMENT ON COLUMN comtsbbssummary.mumm_inqire_bbsctt_id IS '최소조회게시글ID';
COMMENT ON COLUMN comtsbbssummary.top_ntcr_id IS '최고게시자ID';

-- =========== comtssyslogsummary ===========
CREATE TABLE comtssyslogsummary (
  occrrnc_de char(8) NOT NULL,
  svc_nm varchar(255) NOT NULL,
  method_nm varchar(60) NOT NULL,
  creat_co decimal(10,0),
  updt_co decimal(10,0),
  rdcnt decimal(10,0),
  delete_co decimal(10,0),
  outpt_co decimal(10,0),
  error_co decimal(10,0),
  PRIMARY KEY (occrrnc_de, svc_nm, method_nm)
);

CREATE UNIQUE INDEX ux_comtssyslogsummary_pk ON comtssyslogsummary (occrrnc_de, svc_nm, method_nm);
COMMENT ON COLUMN comtssyslogsummary.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtssyslogsummary.svc_nm IS '서비스명';
COMMENT ON COLUMN comtssyslogsummary.method_nm IS '메서드명';
COMMENT ON COLUMN comtssyslogsummary.creat_co IS '생성수';
COMMENT ON COLUMN comtssyslogsummary.updt_co IS '수정수';
COMMENT ON COLUMN comtssyslogsummary.rdcnt IS '조회수';
COMMENT ON COLUMN comtssyslogsummary.delete_co IS '삭제수';
COMMENT ON COLUMN comtssyslogsummary.outpt_co IS '출력수';
COMMENT ON COLUMN comtssyslogsummary.error_co IS '오류수';

-- =========== comtstrsmrcvlogsummary ===========
CREATE TABLE comtstrsmrcvlogsummary (
  occrrnc_de char(20) NOT NULL DEFAULT '',
  trsmrcv_se_code char(3) NOT NULL DEFAULT '',
  provd_instt_id char(8) NOT NULL DEFAULT '',
  provd_sys_id char(8) NOT NULL DEFAULT '',
  provd_svc_id char(8) NOT NULL DEFAULT '',
  requst_instt_id char(8) NOT NULL DEFAULT '',
  requst_sys_id char(8) NOT NULL DEFAULT '',
  rdcnt decimal(10,0),
  error_co decimal(10,0),
  PRIMARY KEY (occrrnc_de, trsmrcv_se_code, provd_instt_id, provd_sys_id, provd_svc_id, requst_instt_id, requst_sys_id)
);

CREATE UNIQUE INDEX ux_comtstrsmrcvlogsummary_pk ON comtstrsmrcvlogsummary (occrrnc_de, trsmrcv_se_code, provd_instt_id, provd_sys_id, provd_svc_id, requst_instt_id, requst_sys_id);
COMMENT ON COLUMN comtstrsmrcvlogsummary.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtstrsmrcvlogsummary.trsmrcv_se_code IS '송수신구분코드';
COMMENT ON COLUMN comtstrsmrcvlogsummary.provd_instt_id IS '제공기관ID';
COMMENT ON COLUMN comtstrsmrcvlogsummary.provd_sys_id IS '제공시스템ID';
COMMENT ON COLUMN comtstrsmrcvlogsummary.provd_svc_id IS '제공서비스ID';
COMMENT ON COLUMN comtstrsmrcvlogsummary.requst_instt_id IS '요청기관ID';
COMMENT ON COLUMN comtstrsmrcvlogsummary.requst_sys_id IS '요청시스템ID';
COMMENT ON COLUMN comtstrsmrcvlogsummary.rdcnt IS '조회수';
COMMENT ON COLUMN comtstrsmrcvlogsummary.error_co IS '오류수';

-- =========== comtsweblogsummary ===========
CREATE TABLE comtsweblogsummary (
  occrrnc_de char(8) NOT NULL DEFAULT '',
  url varchar(200) NOT NULL DEFAULT '',
  rdcnt decimal(10,0),
  PRIMARY KEY (occrrnc_de, url)
);

CREATE UNIQUE INDEX ux_comtsweblogsummary_pk ON comtsweblogsummary (occrrnc_de, url);
COMMENT ON COLUMN comtsweblogsummary.occrrnc_de IS '발생일';
COMMENT ON COLUMN comtsweblogsummary.url IS 'URL';
COMMENT ON COLUMN comtsweblogsummary.rdcnt IS '조회수';

-- =========== comtnprogrmlist ===========
CREATE TABLE comtnprogrmlist (
  progrm_file_nm varchar(60) NOT NULL DEFAULT '',
  progrm_stre_path varchar(100) NOT NULL,
  progrm_korean_nm varchar(60),
  progrm_dc varchar(200),
  url varchar(100) NOT NULL,
  PRIMARY KEY (progrm_file_nm)
);

CREATE UNIQUE INDEX ux_comtnprogrmlist_pk ON comtnprogrmlist (progrm_file_nm);
COMMENT ON COLUMN comtnprogrmlist.progrm_file_nm IS '프로그램파일명';
COMMENT ON COLUMN comtnprogrmlist.progrm_stre_path IS '프로그램저장경로';
COMMENT ON COLUMN comtnprogrmlist.progrm_korean_nm IS '프로그램한글명';
COMMENT ON COLUMN comtnprogrmlist.progrm_dc IS '프로그램설명';
COMMENT ON COLUMN comtnprogrmlist.url IS 'URL';

-- =========== comtntmplatinfo ===========
CREATE TABLE comtntmplatinfo (
  tmplat_id char(20) NOT NULL DEFAULT '',
  tmplat_nm varchar(255),
  tmplat_cours varchar(2000),
  use_at char(1),
  tmplat_se_code char(6),
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP,
  PRIMARY KEY (tmplat_id)
);

CREATE UNIQUE INDEX ux_comtntmplatinfo_pk ON comtntmplatinfo (tmplat_id);
COMMENT ON COLUMN comtntmplatinfo.tmplat_id IS '템플릿ID';
COMMENT ON COLUMN comtntmplatinfo.tmplat_nm IS '템플릿명';
COMMENT ON COLUMN comtntmplatinfo.tmplat_cours IS '템플릿경로';
COMMENT ON COLUMN comtntmplatinfo.use_at IS '사용여부';
COMMENT ON COLUMN comtntmplatinfo.tmplat_se_code IS '템플릿구분코드';
COMMENT ON COLUMN comtntmplatinfo.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN comtntmplatinfo.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN comtntmplatinfo.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN comtntmplatinfo.last_updt_pnttm IS '최종수정시점';

-- =========== comtnmenuinfo ===========
CREATE TABLE comtnmenuinfo (
  menu_nm varchar(60) NOT NULL,
  progrm_file_nm varchar(60) NOT NULL,
  menu_no decimal(20,0) NOT NULL,
  upper_menu_no decimal(20,0),
  menu_ordr decimal(5,0) NOT NULL,
  menu_dc varchar(250),
  relate_image_path varchar(100),
  relate_image_nm varchar(60),
  cntntsuseat char(1),
  PRIMARY KEY (menu_no)
);

CREATE UNIQUE INDEX ux_comtnmenuinfo_pk ON comtnmenuinfo (menu_no);
CREATE INDEX ix_comtnmenuinfo_fk2 ON comtnmenuinfo (progrm_file_nm);
CREATE INDEX ix_comtnmenuinfo_i02 ON comtnmenuinfo (upper_menu_no);
COMMENT ON COLUMN comtnmenuinfo.menu_nm IS '메뉴명';
COMMENT ON COLUMN comtnmenuinfo.progrm_file_nm IS '프로그램파일명';
COMMENT ON COLUMN comtnmenuinfo.menu_no IS '메뉴번호';
COMMENT ON COLUMN comtnmenuinfo.upper_menu_no IS '상위메뉴번호';
COMMENT ON COLUMN comtnmenuinfo.menu_ordr IS '메뉴순서';
COMMENT ON COLUMN comtnmenuinfo.menu_dc IS '메뉴설명';
COMMENT ON COLUMN comtnmenuinfo.relate_image_path IS '관계이미지경로';
COMMENT ON COLUMN comtnmenuinfo.relate_image_nm IS '관계이미지명';
COMMENT ON COLUMN comtnmenuinfo.cntntsuseat IS '메뉴사용여부';

