-- ============================================
-- V7__platform_misc.sql
-- 기타 운영/배치 (9종)
-- 대상 테이블: 9개 (sc_tran, ba_config_cd, batch_opert, batch_schdul, batch_schdul_dfk...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== sc_tran ===========
CREATE TABLE sc_tran (
  tr_num BIGINT,
  tr_senddate date,
  tr_id varchar(16),
  tr_sendstat varchar(1),
  tr_rsltstat varchar(2),
  tr_msgtype varchar(1),
  tr_phone varchar(20),
  tr_callback varchar(20),
  tr_rsltdate date,
  tr_modified date,
  tr_msg varchar(160),
  tr_net varchar(4),
  tr_etc1 varchar(160),
  tr_etc2 varchar(160),
  tr_etc3 varchar(160),
  tr_etc4 varchar(160),
  tr_etc5 varchar(160),
  tr_etc6 varchar(160),
  tr_realsenddate date
);


-- =========== ba_config_cd ===========
CREATE TABLE ba_config_cd (
  code_no INTEGER,
  sys_cd varchar(20),
  code_val varchar(20),
  code_nm varchar(100),
  code_seq INTEGER,
  is_use varchar(1),
  reg_dt TIMESTAMP,
  reg_id varchar(30),
  upd_dt TIMESTAMP,
  upd_id varchar(30),
  code_info varchar(1000),
  sys_nm varchar(100),
  code_cd varchar(20),
  code_id varchar(20),
  p_codeid varchar(20),
  no INTEGER
);

COMMENT ON COLUMN ba_config_cd.code_no IS '설정코드값';
COMMENT ON COLUMN ba_config_cd.sys_cd IS '공통코드';
COMMENT ON COLUMN ba_config_cd.code_val IS '설정값';
COMMENT ON COLUMN ba_config_cd.code_nm IS '설정코드명';
COMMENT ON COLUMN ba_config_cd.code_seq IS '코드순서';
COMMENT ON COLUMN ba_config_cd.is_use IS '상태(Y:활성 , N:비활성)';
COMMENT ON COLUMN ba_config_cd.reg_dt IS '등록일시';
COMMENT ON COLUMN ba_config_cd.reg_id IS '등록자';
COMMENT ON COLUMN ba_config_cd.upd_dt IS '수정일시';
COMMENT ON COLUMN ba_config_cd.upd_id IS '수정자';
COMMENT ON COLUMN ba_config_cd.code_info IS '코드설명';
COMMENT ON COLUMN ba_config_cd.sys_nm IS '공통코드명';

-- =========== batch_opert ===========
CREATE TABLE batch_opert (
  batch_opert_id varchar(20) NOT NULL,
  batch_opert_nm varchar(60),
  batch_progrm varchar(255),
  paramtr varchar(250),
  use_at char(1),
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP NOT NULL,
  PRIMARY KEY (batch_opert_id)
);

CREATE UNIQUE INDEX ux_batch_opert_pk ON batch_opert (batch_opert_id);
COMMENT ON COLUMN batch_opert.batch_opert_id IS '배치작업ID';
COMMENT ON COLUMN batch_opert.batch_opert_nm IS '배치작업명';
COMMENT ON COLUMN batch_opert.batch_progrm IS '배치프로그램';
COMMENT ON COLUMN batch_opert.paramtr IS '파라미터';
COMMENT ON COLUMN batch_opert.use_at IS '사용여부';
COMMENT ON COLUMN batch_opert.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN batch_opert.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN batch_opert.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN batch_opert.last_updt_pnttm IS '최종수정시점';

-- =========== batch_schdul ===========
CREATE TABLE batch_schdul (
  batch_schdul_id varchar(20) NOT NULL,
  batch_opert_id varchar(20) NOT NULL,
  execut_cycle varchar(2),
  execut_schdul_de char(20),
  execut_schdul_hour char(2),
  execut_schdul_mnt char(2),
  execut_schdul_secnd char(2),
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP NOT NULL,
  PRIMARY KEY (batch_schdul_id)
);

CREATE UNIQUE INDEX ux_batch_schdul_pk ON batch_schdul (batch_schdul_id);
COMMENT ON COLUMN batch_schdul.batch_schdul_id IS '배치일정ID';
COMMENT ON COLUMN batch_schdul.batch_opert_id IS '배치작업ID';
COMMENT ON COLUMN batch_schdul.execut_cycle IS '실행주기';
COMMENT ON COLUMN batch_schdul.execut_schdul_de IS '실행일정일';
COMMENT ON COLUMN batch_schdul.execut_schdul_hour IS '실행일정시';
COMMENT ON COLUMN batch_schdul.execut_schdul_mnt IS '실행일정분';
COMMENT ON COLUMN batch_schdul.execut_schdul_secnd IS '실행일정초';
COMMENT ON COLUMN batch_schdul.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN batch_schdul.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN batch_schdul.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN batch_schdul.last_updt_pnttm IS '최종수정시점';

-- =========== batch_schdul_dfk ===========
CREATE TABLE batch_schdul_dfk (
  batch_schdul_id varchar(20) NOT NULL,
  execut_schdul_dfk_se char(1) NOT NULL,
  PRIMARY KEY (batch_schdul_id, execut_schdul_dfk_se),
  CONSTRAINT batch_schdul_dfk_fk1 FOREIGN KEY (batch_schdul_id) REFERENCES batch_schdul (batch_schdul_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX ux_batch_schdul_dfk_pk ON batch_schdul_dfk (batch_schdul_id, execut_schdul_dfk_se);
COMMENT ON COLUMN batch_schdul_dfk.batch_schdul_id IS '배치일정ID';
COMMENT ON COLUMN batch_schdul_dfk.execut_schdul_dfk_se IS '실행일정요일구분';

-- =========== backup_opert ===========
CREATE TABLE backup_opert (
  backup_opert_id varchar(20) NOT NULL,
  backup_opert_nm varchar(60),
  backup_orginl_drctry varchar(255),
  backup_stre_drctry varchar(255),
  cmprs_se varchar(2),
  execut_cycle varchar(2),
  execut_schdul_de char(20),
  execut_schdul_hour char(2),
  execut_schdul_mnt char(2),
  execut_schdul_secnd char(2),
  use_at char(1),
  frst_register_id varchar(20),
  frst_regist_pnttm TIMESTAMP,
  last_updusr_id varchar(20),
  last_updt_pnttm TIMESTAMP NOT NULL,
  PRIMARY KEY (backup_opert_id)
);

CREATE UNIQUE INDEX ux_backup_opert_pk ON backup_opert (backup_opert_id);
COMMENT ON COLUMN backup_opert.backup_opert_id IS '백업작업ID';
COMMENT ON COLUMN backup_opert.backup_opert_nm IS '백업작업명';
COMMENT ON COLUMN backup_opert.backup_orginl_drctry IS '백업원본디렉토리';
COMMENT ON COLUMN backup_opert.backup_stre_drctry IS '백업저장디렉토리';
COMMENT ON COLUMN backup_opert.cmprs_se IS '압축구분';
COMMENT ON COLUMN backup_opert.execut_cycle IS '실행주기';
COMMENT ON COLUMN backup_opert.execut_schdul_de IS '실행일정일';
COMMENT ON COLUMN backup_opert.execut_schdul_hour IS '실행일정시';
COMMENT ON COLUMN backup_opert.execut_schdul_mnt IS '실행일정분';
COMMENT ON COLUMN backup_opert.execut_schdul_secnd IS '실행일정초';
COMMENT ON COLUMN backup_opert.use_at IS '사용여부';
COMMENT ON COLUMN backup_opert.frst_register_id IS '최초등록자ID';
COMMENT ON COLUMN backup_opert.frst_regist_pnttm IS '최초등록시점';
COMMENT ON COLUMN backup_opert.last_updusr_id IS '최종수정자ID';
COMMENT ON COLUMN backup_opert.last_updt_pnttm IS '최종수정시점';

-- =========== web_log ===========
CREATE TABLE web_log (
  requst_id varchar(20) NOT NULL,
  occrrnc_de TIMESTAMP,
  url varchar(200),
  rqester_id varchar(20),
  rqester_ip varchar(23),
  PRIMARY KEY (requst_id)
);

CREATE UNIQUE INDEX ux_web_log_pk ON web_log (requst_id);
COMMENT ON COLUMN web_log.requst_id IS '요청ID';
COMMENT ON COLUMN web_log.occrrnc_de IS '발생일';
COMMENT ON COLUMN web_log.url IS 'URL';
COMMENT ON COLUMN web_log.rqester_id IS '요청자ID';
COMMENT ON COLUMN web_log.rqester_ip IS '요청자IP';

-- =========== www_poll ===========
CREATE TABLE www_poll (
  poll_id BIGINT,
  start_dt varchar(10),
  end_dt varchar(10),
  isuse varchar(1),
  title varchar(500),
  is_show varchar(1)
);


-- =========== www_poll_item ===========
CREATE TABLE www_poll_item (
  poll_id BIGINT,
  poll_item_id BIGINT,
  viw varchar(100),
  seq BIGINT,
  cnt BIGINT,
  subject_nm varchar(100)
);


