-- ============================================
-- V8__legacy_tb_member.sql
-- 윌비스 회원 (tb_ma_*, tb_tm_users 등)
-- 대상 테이블: 10개 (tb_ma_member, tb_ma_member_category, tb_ma_member_main_category, tb_ma_member_prf, tb_ma_member_series...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_ma_member ===========
CREATE TABLE tb_ma_member (
  user_id varchar(30),
  user_nm varchar(50),
  user_nicknm varchar(100),
  user_position varchar(100),
  sex varchar(1),
  user_role varchar(20),
  admin_role varchar(20),
  user_pwd varchar(100),
  birth_day varchar(8),
  email varchar(100),
  zip_code varchar(10),
  address1 varchar(200),
  address2 varchar(200),
  category_code varchar(20),
  user_point varchar(50),
  payment varchar(50),
  pic1 varchar(100),
  pic2 varchar(100),
  pic3 varchar(100),
  pic4 varchar(100),
  account varchar(100),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  off_payment varchar(50),
  off_pic1 varchar(100),
  off_pic2 varchar(100),
  off_pic3 varchar(100),
  off_pic4 varchar(100),
  off_pic5 varchar(100),
  on_openyn varchar(1),
  off_openyn varchar(1),
  off_movie_payment varchar(50),
  title varchar(4000),
  off_title varchar(500),
  profile_summary varchar(2000),
  book_log_summary varchar(2000),
  join_channel varchar(10),
  job varchar(10),
  exam_req varchar(10),
  f_cat_cd varchar(50),
  f_area varchar(55),
  s_cat_cd varchar(50),
  s_area varchar(55),
  info_req varchar(20),
  event_req varchar(20),
  sbj_req varchar(10),
  event_req_etc varchar(100),
  isok_sms varchar(1),
  isok_email varchar(1),
  coop_cd varchar(10),
  on_url varchar(500),
  off_url varchar(500),
  pic5 varchar(100),
  brd_yn varchar(1),
  off_brd_yn varchar(1),
  prof_html varchar(2000),
  referral_yn varchar(1),
  prf_brd_of varchar(1),
  prf_brd_on varchar(1),
  macaddress_yn varchar(1),
  teacheronoff_yn varchar(1),
  prf_onpic1 varchar(100),
  prf_onpic2 varchar(100),
  prf_onpic3 varchar(100),
  prf_offpic1 varchar(100),
  prf_offpic2 varchar(100),
  prf_offpic3 varchar(100),
  prf_listonbanner varchar(100),
  prf_listoffbanner varchar(100),
  prf_toponimg varchar(100),
  prf_topoffimg varchar(100),
  u_area varchar(2),
  remark varchar(2000),
  memo varchar(2000),
  profile varchar(2000)
);


-- =========== tb_ma_member_category ===========
CREATE TABLE tb_ma_member_category (
  user_id varchar(30),
  category_code varchar(20),
  seq BIGINT,
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  off_seq BIGINT
);


-- =========== tb_ma_member_main_category ===========
CREATE TABLE tb_ma_member_main_category (
  user_id varchar(30),
  category_code varchar(20),
  seq BIGINT,
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  subject_cd varchar(50)
);


-- =========== tb_ma_member_prf ===========
CREATE TABLE tb_ma_member_prf (
  user_id varchar(30),
  user_nm varchar(50),
  user_nicknm varchar(100),
  user_position varchar(100),
  sex varchar(1),
  user_role varchar(20),
  admin_role varchar(20),
  user_pwd varchar(100),
  birth_day varchar(8),
  email varchar(100),
  zip_code varchar(10),
  address1 varchar(200),
  address2 varchar(200),
  category_code varchar(20),
  user_point varchar(50),
  remark BYTEA,
  memo BYTEA,
  payment varchar(50),
  pic1 varchar(100),
  pic2 varchar(100),
  pic3 varchar(100),
  pic4 varchar(100),
  profile BYTEA,
  account varchar(100),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  off_payment varchar(50),
  off_profile BYTEA,
  off_pic1 varchar(100),
  off_pic2 varchar(100),
  off_pic3 varchar(100),
  off_pic4 varchar(100),
  off_pic5 varchar(100),
  on_openyn varchar(1),
  off_openyn varchar(1),
  off_movie_payment varchar(50),
  title varchar(4000),
  book_log BYTEA,
  yplan BYTEA,
  lecinfo BYTEA,
  off_title varchar(4000),
  off_yplan BYTEA,
  off_lecinfo BYTEA,
  profile_summary varchar(4000),
  book_log_summary varchar(4000)
);


-- =========== tb_ma_member_series ===========
CREATE TABLE tb_ma_member_series (
  user_id varchar(30),
  series_cd varchar(20),
  seq BIGINT,
  off_seq BIGINT,
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_ma_member_subject ===========
CREATE TABLE tb_ma_member_subject (
  user_id varchar(30),
  subject_cd varchar(50),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_tm_users ===========
CREATE TABLE tb_tm_users (
  idx BIGINT,
  userid varchar(30),
  username varchar(30),
  tel varchar(20),
  phone varchar(20),
  email varchar(50),
  admuserid varchar(30),
  admusername varchar(20),
  allocdate date,
  usertype varchar(1),
  oriadmuserid varchar(30),
  oriadmusername varchar(30),
  oriallocdate date,
  oriusertype varchar(1),
  allocadmin varchar(30),
  dbsouace varchar(20),
  idx_tmboard BIGINT
);


-- =========== tb_tm_admin ===========
CREATE TABLE tb_tm_admin (
  idx BIGINT,
  adminid varchar(30),
  adminname varchar(30),
  deleteflag varchar(1),
  reg_dt date NOT NULL
);


-- =========== tm_device_history ===========
CREATE TABLE tm_device_history (
  user_id varchar(30),
  device_id varchar(200),
  device_gubun varchar(200),
  pc_useyn varchar(1),
  pc_reg_dt date,
  pc_cancel_dt date,
  device_desc varchar(4000),
  admin_id varchar(30),
  seq BIGINT,
  mobile_useyn varchar(1),
  mobile_cancel_dt date,
  mobile_reg_dt date
);


-- =========== tm_ist ===========
CREATE TABLE tm_ist (
  id varchar(20),
  name varchar(20),
  hp varchar(20)
);


