-- ============================================
-- V9__legacy_tb_lecture.sql
-- 윌비스 강의 마스터/영상
-- 대상 테이블: 17개 (tb_lec_mst, tb_lec_mst_memo, tb_lec_bridge, tb_lec_jong, tb_movie...)
-- 자동 생성: scripts/db-migration/generate_v_files.py
-- ============================================

-- ============================================
-- Auto-generated by mariadb_to_pg.py
-- 입력: acm_basic.schema.sql (MariaDB 11.8)
-- 출력: PostgreSQL 15 호환 DDL
-- ⚠️  자동 변환 결과 — 수동 검증 필수
-- 마커: /*PG_TODO_ON_UPDATE*/, /*PG_TODO: ...*/ → 트리거/수동 처리
-- ============================================

-- =========== tb_lec_mst ===========
CREATE TABLE tb_lec_mst (
  seq BIGINT,
  leccode varchar(30),
  category_cd varchar(20),
  learning_cd varchar(20),
  subject_teacher varchar(30),
  subject_teacher_payment varchar(50),
  subject_title varchar(200),
  subject_keyword varchar(200),
  subject_period BIGINT,
  subject_off_open_year varchar(4),
  subject_off_open_month varchar(2),
  subject_off_open_day varchar(2),
  subject_discount BIGINT,
  subject_price BIGINT,
  subject_point BIGINT,
  subject_movie BIGINT,
  subject_pmp BIGINT,
  subject_movie_pmp BIGINT,
  subject_movie_mp4 BIGINT,
  subject_movie_vod_mp4 BIGINT,
  subject_sumnail varchar(200),
  subject_event_image varchar(200),
  subject_outside varchar(1),
  subject_option varchar(200),
  subject_isuse varchar(1),
  subject_sjt_cd varchar(50),
  two_subject varchar(30),
  three_subject varchar(30),
  five_subject varchar(30),
  subject_vod_default_path varchar(500),
  subject_mp4_default_path varchar(500),
  subject_pmp_default_path varchar(500),
  subject_pass varchar(50),
  subject_jang varchar(1),
  re_course varchar(30),
  lec_schedule varchar(50),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  lec_type_choice varchar(1),
  rec_gubun varchar(1),
  lec_gubun varchar(1),
  mov_ing varchar(1),
  gift_flag varchar(1),
  gift_coupon_ccode varchar(40),
  gift_leccode varchar(40),
  coupon_name varchar(200),
  gift_name varchar(200),
  teacherno BIGINT,
  icon_gubun varchar(10),
  mo_coupon_name varchar(200),
  mo_coupon_ccode varchar(40),
  free_tab varchar(10),
  subject_monitormode varchar(100),
  subject_wide_default_path varchar(500),
  must_prf_img varchar(200),
  sel_prf_img varchar(200),
  subject_desc_varchar varchar(4000),
  subject_memo_varchar varchar(4000),
  plan_varchar varchar(4000)
);


-- =========== tb_lec_mst_memo ===========
CREATE TABLE tb_lec_mst_memo (
  bridge_leccode varchar(30),
  movie_order1 BIGINT,
  movie_order2 BIGINT,
  position varchar(50),
  mst_text varchar(4000)
);


-- =========== tb_lec_bridge ===========
CREATE TABLE tb_lec_bridge (
  seq BIGINT,
  bridge_leccode varchar(30),
  leccode varchar(30),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_lec_jong ===========
CREATE TABLE tb_lec_jong (
  seq BIGINT,
  leccode varchar(30),
  mst_leccode varchar(30),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  sort BIGINT,
  gubun varchar(1)
);


-- =========== tb_movie ===========
CREATE TABLE tb_movie (
  movie_no BIGINT,
  leccode varchar(30),
  movie_name varchar(300),
  movie_desc varchar(300),
  movie_url varchar(800),
  movie_filename1 varchar(500),
  mp4_url varchar(800),
  movie_filename2 varchar(500),
  movie_filename3 varchar(500),
  movie_data_file_yn varchar(1),
  movie_data_filename varchar(500),
  movie_time BIGINT,
  movie_order1 BIGINT,
  movie_order2 BIGINT,
  movie_free_flag varchar(1),
  pmp_url varchar(800),
  pmp_filename varchar(500),
  stop varchar(1),
  wide_url varchar(800),
  movie_filename4 varchar(500)
);


-- =========== tb_mymovie ===========
CREATE TABLE tb_mymovie (
  userid varchar(30),
  orderno varchar(20),
  package_no varchar(30),
  lecture_no varchar(30),
  movie_no BIGINT,
  curr_time BIGINT,
  total_time BIGINT,
  study_percent BIGINT,
  study_time BIGINT,
  total_baesu BIGINT,
  baesu_time BIGINT,
  last_position_time BIGINT
);


-- =========== tb_mylecture ===========
CREATE TABLE tb_mylecture (
  userid varchar(30),
  orderno varchar(20),
  package_no varchar(30),
  lecture_no varchar(30),
  start_date date,
  end_date date,
  period BIGINT,
  study_percent BIGINT,
  stop_lecture varchar(1),
  free_id varchar(30),
  plus_buy BIGINT,
  playyn varchar(1),
  reg_dt date,
  add_length BIGINT,
  firststart_date date,
  parent_orderno varchar(20),
  gift_yn varchar(1)
);


-- =========== tb_mylecture_pause ===========
CREATE TABLE tb_mylecture_pause (
  user_id varchar(20),
  orderno varchar(20),
  package_no varchar(30),
  lecture_no varchar(30),
  mylecture_paused varchar(1),
  mylecture_paused_count BIGINT,
  mylecture_paused_period BIGINT,
  mylecture_paused_date1 date,
  mylecture_paused_period1 BIGINT,
  mylecture_paused_date2 date,
  mylecture_paused_period2 BIGINT,
  mylecture_paused_date3 date,
  mylecture_paused_period3 BIGINT
);


-- =========== tb_subject_info ===========
CREATE TABLE tb_subject_info (
  subject_cd varchar(50),
  subject_nm varchar(500),
  subject_short_nm varchar(60),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  use_on varchar(1),
  use_off varchar(1)
);


-- =========== tb_subject_category ===========
CREATE TABLE tb_subject_category (
  subject_cd varchar(50),
  category_code varchar(50)
);


-- =========== tb_subject_series ===========
CREATE TABLE tb_subject_series (
  subject_cd varchar(50),
  series_cd varchar(50)
);


-- =========== tb_category_info ===========
CREATE TABLE tb_category_info (
  id BIGINT,
  code varchar(20),
  name varchar(50),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  use_on varchar(1),
  use_off varchar(1),
  p_code varchar(20),
  code_val varchar(20),
  ordr BIGINT
);


-- =========== tb_category_series ===========
CREATE TABLE tb_category_series (
  seq BIGINT,
  cat_cd varchar(20),
  srs_cd varchar(20),
  ordr BIGINT,
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


-- =========== tb_category_subject_order ===========
CREATE TABLE tb_category_subject_order (
  onoff_div varchar(1),
  category_code varchar(50),
  subject_cd varchar(50),
  idx BIGINT
);


-- =========== tb_main_category_subject_order ===========
CREATE TABLE tb_main_category_subject_order (
  onoff_div varchar(1),
  category_code varchar(50),
  subject_cd varchar(50),
  idx BIGINT
);


-- =========== tb_series_info ===========
CREATE TABLE tb_series_info (
  srs_cd varchar(20),
  srs_nm varchar(50),
  ordr BIGINT,
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30),
  p_srscd varchar(20)
);


-- =========== tb_learning_form_info ===========
CREATE TABLE tb_learning_form_info (
  lec_div varchar(10),
  code varchar(20),
  name varchar(50),
  isuse varchar(1),
  reg_dt date,
  reg_id varchar(30),
  upd_dt date,
  upd_id varchar(30)
);


