-- View definitions extracted from acm_basic

-- =============================
-- VIEW: comvnusermaster
-- =============================
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `comvnusermaster` AS select `gnrl_mber`.`ESNTL_ID` AS `ESNTL_ID`,`gnrl_mber`.`MBER_ID` AS `USER_ID`,`gnrl_mber`.`PASSWORD` AS `PASSWORD`,`gnrl_mber`.`MBER_NM` AS `USER_NM`,`gnrl_mber`.`ZIP` AS `ZIP`,`gnrl_mber`.`ADRES` AS `ADRES`,`gnrl_mber`.`MBER_EMAIL_ADRES` AS `MBER_EMAIL_ADRES`,' ' AS `Name_exp_8`,'GNR' AS `USER_SE`,' ' AS `ORGNZT_ID` from `gnrl_mber` union all select `emplyr_info`.`ESNTL_ID` AS `ESNTL_ID`,`emplyr_info`.`EMPLYR_ID` AS `EMPLYR_ID`,`emplyr_info`.`PASSWORD` AS `PASSWORD`,`emplyr_info`.`USER_NM` AS `USER_NM`,`emplyr_info`.`ZIP` AS `ZIP`,`emplyr_info`.`HOUSE_ADRES` AS `HOUSE_ADRES`,`emplyr_info`.`EMAIL_ADRES` AS `EMAIL_ADRES`,`emplyr_info`.`GROUP_ID` AS `GROUP_ID`,'USR' AS `USER_SE`,`emplyr_info`.`ORGNZT_ID` AS `ORGNZT_ID` from `emplyr_info` union all select `entrprs_mber`.`ESNTL_ID` AS `ESNTL_ID`,`entrprs_mber`.`ENTRPRS_MBER_ID` AS `ENTRPRS_MBER_ID`,`entrprs_mber`.`ENTRPRS_MBER_PASSWORD` AS `ENTRPRS_MBER_PASSWORD`,`entrprs_mber`.`CMPNY_NM` AS `CMPNY_NM`,`entrprs_mber`.`ZIP` AS `ZIP`,`entrprs_mber`.`ADRES` AS `ADRES`,`entrprs_mber`.`APPLCNT_EMAIL_ADRES` AS `APPLCNT_EMAIL_ADRES`,' ' AS `Name_exp_8`,'ENT' AS `USER_SE`,' ' AS `ORGNZT_ID` from `entrprs_mber` order by `ESNTL_ID`
;

-- =============================
-- VIEW: v_inquiry
-- =============================
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_inquiry` AS select 'L' AS `source`,`L`.`BOARD_SEQ` AS `inquiry_id`,`L`.`REG_ID` AS `user_id`,`L`.`CREATENAME` AS `user_name`,`L`.`SUBJECT` AS `title`,left(convert(`L`.`CONTENT` using utf8mb4),65535) AS `body`,`L`.`REG_DT` AS `inquiry_date`,NULL AS `predicted_category`,NULL AS `predicted_confidence`,NULL AS `classified_by_model`,NULL AS `classified_at`,`M`.`std_category` AS `actual_category`,`L`.`COUNSELOR_ID` AS `assigned_to`,0 AS `reroute_count`,left(convert(`L`.`ANSWER` using utf8mb4),65535) AS `answer_body`,`L`.`COUNSELOR_ID` AS `answered_by`,case when `L`.`ANSWER` is not null then `L`.`UPD_DT` else NULL end AS `answered_at`,case `L`.`ACTION_YN` when 'Y' then 'RESOLVED' else 'OPEN' end AS `resolution_state`,NULL AS `user_satisfaction`,`L`.`REG_DT` AS `reg_dt`,`L`.`UPD_DT` AS `upd_dt`,'N' AS `is_deleted` from (`tb_board_cs` `L` left join `tb_category_mapping` `M` on(`M`.`legacy_cs_div` = `L`.`CS_DIV` and (`M`.`legacy_cs_kind` = coalesce(`L`.`CS_KIND`,'') or `M`.`legacy_cs_kind` = ''))) union all select 'N' AS `source`,cast(`N`.`inquiry_id` as char(20) charset utf8mb4) AS `inquiry_id`,`N`.`user_id` AS `user_id`,`N`.`user_name` AS `user_name`,`N`.`title` AS `title`,`N`.`body` AS `body`,`N`.`inquiry_date` AS `inquiry_date`,`N`.`predicted_category` AS `predicted_category`,`N`.`predicted_confidence` AS `predicted_confidence`,`N`.`classified_by_model` AS `classified_by_model`,`N`.`classified_at` AS `classified_at`,`N`.`actual_category` AS `actual_category`,`N`.`assigned_to` AS `assigned_to`,`N`.`reroute_count` AS `reroute_count`,`N`.`answer_body` AS `answer_body`,`N`.`answered_by` AS `answered_by`,`N`.`answered_at` AS `answered_at`,`N`.`resolution_state` AS `resolution_state`,`N`.`user_satisfaction` AS `user_satisfaction`,`N`.`reg_dt` AS `reg_dt`,`N`.`upd_dt` AS `upd_dt`,`N`.`is_deleted` AS `is_deleted` from `tb_inquiry` `N` where `N`.`is_deleted` = 'N'
;

